act_dict = {
    0: {'all_key': '不倫する', 'act': '不倫する', 'act_noun': '不倫', 'eng': 'affair', 'act_target': '不倫相手',
        'act_connection': '不倫', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
        '2act_w': '', '2act_noun': '', 'a_ad': 0},
    1: {'all_key': '二股する', 'act': '二股する', 'act_noun': '二股', 'eng': 'second_crotch', 'act_target': '二股相手',
        'act_connection': '二股', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
        '2act_w': '', '2act_noun': '', 'a_ad': 0},
    2: {'all_key': '仲良くなる', 'act': '仲良くなる', 'act_noun': '仲良し', 'eng': 'a_good_friend', 'act_target': '仲の良い異性',
        'act_connection': '仲良し', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
        '2act_w': '', '2act_noun': '', 'a_ad': 3},
    3: {'all_key': '両思いになる', 'act': '両思いになる', 'act_noun': '両思い', 'eng': 'bothersome', 'act_target': '両思いの彼女',
        'act_connection': '両思い', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
        '2act_w': '', '2act_noun': '', 'a_ad': 3},
    4: {'all_key': 'W不倫する', 'act': 'W不倫する', 'act_noun': 'W不倫', 'eng': 'w_affair', 'act_target': 'W不倫相手',
        'act_connection': 'W不倫', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
        '2act_w': '', '2act_noun': '', 'a_ad': 0},
    5: {'all_key': 'ワンナイトラブする', 'act': 'ワンナイトラブする', 'act_noun': 'ワンナイトラブ', 'eng': 'one_night_love',
        'act_target': 'ワンナイトラブの相手', 'act_connection': 'ワンナイトラブ', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
        'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    6: {'all_key': '昼間会う', 'act': '昼間会う', 'act_noun': '昼間の密会', 'eng': 'daytime', 'act_target': '密会相手',
        'act_connection': '昼間の密会', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
        '2act_w': '', '2act_noun': '', 'a_ad': 1},
    7: {'all_key': '電話で話す', 'act': '電話で話す', 'act_noun': '電話', 'eng': 'phone', 'act_target': '電話友達',
        'act_connection': '電話', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
        '2act_w': '', '2act_noun': '', 'a_ad': 3},
    8: {'all_key': '初体験する', 'act': '初体験する', 'act_noun': '初体験', 'eng': 'first_experience', 'act_target': '初体験相手',
        'act_connection': '初体験', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
        '2act_w': '', '2act_noun': '', 'a_ad': 1},
    9: {'all_key': 'NTRプレイする', 'act': 'NTRプレイする', 'act_noun': 'NTRプレイ', 'eng': 'ntr_play',
        'act_target': 'NTR相手', 'act_connection': 'NTRプレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
        'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    10: {'all_key': '初セックスする', 'act': '初セックスする', 'act_noun': '初セックス', 'eng': 'first_sex',
         'act_target': '初セックスの相手', 'act_connection': '初セックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    11: {'all_key': '筆おろしする', 'act': '筆おろしする', 'act_noun': '筆おろし', 'eng': 'brush', 'act_target': '筆おろし相手',
         'act_connection': '筆おろし', 'a_sex': 'm', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    12: {'all_key': '中出しする', 'act': '中出しする', 'act_noun': '中出し', 'eng': 'creampie', 'act_target': '中出し相手',
         'act_connection': '中出し', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    13: {'all_key': '制服プレイする', 'act': '制服プレイする', 'act_noun': '制服プレイ', 'eng': 'uniform_play',
         'act_target': '制服プレイの相手', 'act_connection': '制服プレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    14: {'all_key': '媚薬セックスする', 'act': '媚薬セックスする', 'act_noun': '媚薬セックス', 'eng': 'glaze_sex',
         'act_target': '媚薬セックスの相手', 'act_connection': '媚薬セックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    15: {'all_key': '射精管理してもらう', 'act': '射精管理してもらう', 'act_noun': '射精管理', 'eng': 'cumshot_management',
         'act_target': '射精管理者', 'act_connection': '射精管理', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    16: {'all_key': 'ハメ撮りする', 'act': 'ハメ撮りする', 'act_noun': 'ハメ撮り', 'eng': 'goning', 'act_target': 'ハメ撮り相手',
         'act_connection': 'ハメ撮り', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    17: {'all_key': '青姦する', 'act': '青姦する', 'act_noun': '青カン', 'eng': 'blue_can', 'act_target': '青カン相手',
         'act_connection': '青カン', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    18: {'all_key': '素股する', 'act': '素股する', 'act_noun': '素股', 'eng': 'intercourse',
         'act_target': '素股してくれる<!--woman-->', 'act_connection': '素股', 'a_sex': 'm', 'ignore_a': [],
         'obj_p': 'と', 'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    19: {'all_key': '乱交する', 'act': '乱交する', 'act_noun': '乱交', 'eng': 'orgy', 'act_target': '乱交パートナー',
         'act_connection': '乱交', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    20: {'all_key': 'セクハラプレイする', 'act': 'セクハラプレイする', 'act_noun': 'セクハラプレイ', 'eng': 'sexual_harassment',
         'act_target': 'セクハラ相手', 'act_connection': 'セクハラプレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    21: {'all_key': '顔面騎乗してもらう', 'act': '顔面騎乗してもらう', 'act_noun': '顔面騎乗', 'eng': 'sitting_up',
         'act_target': '顔面騎乗女子', 'act_connection': '顔面騎乗', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    22: {'all_key': 'パイズリしてもらう', 'act': 'パイズリしてもらう', 'act_noun': 'パイズリ', 'eng': 'titty_fuck',
         'act_target': 'パイズリ巨乳女子', 'act_connection': 'パイズリ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    23: {'all_key': 'カーセックスする', 'act': 'カーセックスする', 'act_noun': 'カーセックス', 'eng': 'car_sex',
         'act_target': 'カーセックス好き', 'act_connection': 'カーセックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    24: {'all_key': 'オフパコする', 'act': 'オフパコする', 'act_noun': 'オフパコ', 'eng': 'off_park', 'act_target': 'オフパコ好き',
         'act_connection': 'オフパコ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    25: {'all_key': '生パコする', 'act': '生パコする', 'act_noun': '生パコ', 'eng': 'paca', 'act_target': '生パコ相手',
         'act_connection': '生パコ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    26: {'all_key': '複数プレイする', 'act': '複数プレイする', 'act_noun': '複数プレイ', 'eng': 'multiple_play',
         'act_target': '複数プレイ相手', 'act_connection': '複数プレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    27: {'all_key': '痴漢ごっこする', 'act': '痴漢ごっこする', 'act_noun': '痴漢プレイ', 'eng': 'pervert_play',
         'act_target': '痴漢パートナー', 'act_connection': '痴漢プレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    28: {'all_key': 'オナニー鑑賞する', 'act': 'オナニー鑑賞する', 'act_noun': 'オナニー鑑賞', 'eng': 'masturbation_appreciation',
         'act_target': 'オナニー好き', 'act_connection': 'オナニー鑑賞', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    29: {'all_key': 'タダマンする', 'act': 'タダマンする', 'act_noun': 'タダマン', 'eng': 'tadaman', 'act_target': 'タダマンの相手',
         'act_connection': 'タダマン', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    30: {'all_key': '宅飲みセックスする', 'act': '宅飲みセックスする', 'act_noun': '宅飲みセックス', 'eng': 'house_tort_free_sex',
         'act_target': '宅飲みセックスの相手', 'act_connection': '宅飲みセックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    31: {'all_key': '3Pする', 'act': '3Pする', 'act_noun': '3P', 'eng': 'threesome', 'act_target': '3Pパートナー',
         'act_connection': '3P', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    32: {'all_key': '浮気する', 'act': '浮気する', 'act_noun': '浮気', 'eng': 'flirt', 'act_target': '浮気相手',
         'act_connection': '浮気', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 0},
    33: {'all_key': 'エロメールする', 'act': 'エロメールする', 'act_noun': 'エロメール', 'eng': 'ero_mail',
         'act_target': 'エロメール相手', 'act_connection': 'エロメール', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    34: {'all_key': 'チャットエッチする', 'act': 'チャットエッチする', 'act_noun': 'チャットエッチ', 'eng': 'chat_h',
         'act_target': 'チャエッチ相手', 'act_connection': 'チャエッチ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    35: {'all_key': 'メールエッチする', 'act': 'メールエッチする', 'act_noun': 'メールエッチ', 'eng': 'e_mail_h',
         'act_target': 'メールエッチ相手', 'act_connection': 'メールエッチ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    36: {'all_key': 'テレフォンセックスする', 'act': 'テレフォンセックスする', 'act_noun': 'テレフォンセックス', 'eng': 'telephone_sex',
         'act_target': 'テレフォンセックス相手', 'act_connection': 'テレフォンセックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    37: {'all_key': '童貞を捨てる', 'act': '童貞を捨てる', 'act_noun': '童貞卒業', 'eng': 'graduation',
         'act_target': '童貞卒業させてくれる<!--woman-->', 'act_connection': '童貞卒業', 'a_sex': 'm', 'ignore_a': [],
         'obj_p': 'と', 'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    38: {'all_key': 'エッチメールする', 'act': 'エッチメールする', 'act_noun': 'エッチメール', 'eng': 'h_mail',
         'act_target': 'エッチメール相手', 'act_connection': 'エッチメール', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    39: {'all_key': '孕ませる', 'act': '孕ませる', 'act_noun': '孕ませセックス', 'eng': 'pregnant', 'act_target': '孕ませセックス相手',
         'act_connection': '孕ませセックス', 'a_sex': 'm', 'ignore_a': [], 'obj_p': 'を', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 0},
    40: {'all_key': 'SMプレイする', 'act': 'SMプレイする', 'act_noun': 'SMプレイ', 'eng': 'sm_play', 'act_target': 'SMパートナー',
         'act_connection': 'SMプレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    41: {'all_key': '飲み会する', 'act': '飲み会する', 'act_noun': '飲み会', 'eng': 'drinking_party', 'act_target': '飲み仲間',
         'act_connection': '飲み会', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    42: {'all_key': 'サシ呑みする', 'act': 'サシ呑みする', 'act_noun': 'サシ呑み', 'eng': 'drunk', 'act_target': 'サシ呑み相手',
         'act_connection': 'サシ呑み', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    43: {'all_key': 'キスする', 'act': 'キスする', 'act_noun': 'キス', 'eng': 'kiss', 'act_target': 'キス相手',
         'act_connection': 'キス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    44: {'all_key': 'ペッティングする', 'act': 'ペッティングする', 'act_noun': 'ペッティング', 'eng': 'petting',
         'act_target': 'ペッティング相手', 'act_connection': 'ペッティング', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    45: {'all_key': '指マンする', 'act': '指マンする', 'act_noun': '指マン', 'eng': 'finger_man', 'act_target': '指マン好き',
         'act_connection': '指マン', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    46: {'all_key': '潮吹きさせる', 'act': '潮吹きさせる', 'act_noun': '潮吹き', 'eng': 'squirting', 'act_target': '潮吹き女子',
         'act_connection': '潮吹き', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'を', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    47: {'all_key': '玩具プレイする', 'act': '玩具プレイする', 'act_noun': '玩具プレイ', 'eng': 'toy_play', 'act_target': '玩具好き',
         'act_connection': '玩具プレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    48: {'all_key': 'クンニする', 'act': 'クンニする', 'act_noun': 'クンニ', 'eng': 'cunnilingus', 'act_target': 'クンニ好き',
         'act_connection': 'クンニ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'て', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    49: {'all_key': 'フェラチオしてもらう', 'act': 'フェラチオしてもらう', 'act_noun': 'フェラチオ', 'eng': 'blowjob',
         'act_target': 'フェラチオ名人', 'act_connection': 'フェラチオ', 'a_sex': 'm', 'ignore_a': [], 'obj_p': 'に',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    50: {'all_key': '割り切りする', 'act': '割り切りする', 'act_noun': '割り切り', 'eng': 'division', 'act_target': '割り切り女子',
         'act_connection': '割り切り', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 0},
    51: {'all_key': '援助交際する', 'act': '援助交際する', 'act_noun': '援交', 'eng': 'support', 'act_target': '援交女子',
         'act_connection': '援交', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 0},
    52: {'all_key': 'パパ活する', 'act': 'パパ活する', 'act_noun': 'パパ活', 'eng': 'dad', 'act_target': 'パパ活女子',
         'act_connection': 'パパ活', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 0},
    53: {'all_key': 'ママ活する', 'act': 'ママ活する', 'act_noun': 'ママ活', 'eng': 'mommy', 'act_target': 'ママ活女性',
         'act_connection': 'ママ活', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 0},
    54: {'all_key': '結婚する', 'act': '結婚する', 'act_noun': '結婚', 'eng': 'marriage', 'act_target': '結婚相手',
         'act_connection': '結婚', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    55: {'all_key': '婚活する', 'act': '婚活する', 'act_noun': '婚活', 'eng': 'marriage_activity', 'act_target': '婚活対象',
         'act_connection': '婚活', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    56: {'all_key': '彼女を作る', 'act': '彼女を作る', 'act_noun': '彼女探し', 'eng': 'girlfriend', 'act_target': '彼女',
         'act_connection': '彼女探し', 'a_sex': 'm', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    57: {'all_key': '交際する', 'act': '交際する', 'act_noun': '交際', 'eng': 'dating', 'act_target': '交際相手',
         'act_connection': '交際', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    58: {'all_key': '恋愛する', 'act': '恋愛する', 'act_noun': '恋愛', 'eng': 'love', 'act_target': '恋人',
         'act_connection': '恋愛', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    59: {'all_key': '告白する', 'act': '告白する', 'act_noun': '告白', 'eng': 'confession', 'act_target': '告白対象',
         'act_connection': '告白', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    60: {'all_key': '失恋する', 'act': '失恋する', 'act_noun': '失恋', 'eng': 'broken_heart', 'act_target': '失恋相手',
         'act_connection': '失恋', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    61: {'all_key': '出会う', 'act': '出会う', 'act_noun': '出会い', 'eng': 'encounter', 'act_target': '出会いの相手',
         'act_connection': '出会い', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    62: {'all_key': 'セフレを作る', 'act': 'セフレを作る', 'act_noun': 'セフレ探し', 'eng': 'sex_friend', 'act_target': 'セフレ',
         'act_connection': 'セフレ探し', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    63: {'all_key': '恋活する', 'act': '恋活する', 'act_noun': '恋活', 'eng': 'lover', 'act_target': '恋活対象',
         'act_connection': '恋活', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    64: {'all_key': 'メールする', 'act': 'メールする', 'act_noun': 'メール', 'eng': 'email', 'act_target': 'メール相手',
         'act_connection': 'メール', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    65: {'all_key': '純粋なメル友を作る', 'act': '純粋なメル友を作る', 'act_noun': '純粋なメル友探し', 'eng': 'pure_mel_friend',
         'act_target': '純粋なメル友', 'act_connection': '純粋なメル友探し', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    66: {'all_key': '女友達を作る', 'act': '女友達を作る', 'act_noun': '女友達探し', 'eng': 'female_friend', 'act_target': '女友達',
         'act_connection': '女友達探し', 'a_sex': 'm', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    67: {'all_key': '趣味友を作る', 'act': '趣味友を作る', 'act_noun': '趣味友探し', 'eng': 'hobbies_friend',
         'act_target': '趣味友', 'act_connection': '趣味友探し', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    68: {'all_key': 'ゲーム仲間を作る', 'act': 'ゲーム仲間を作る', 'act_noun': 'ゲーム仲間探し', 'eng': 'game_companions',
         'act_target': 'ゲーム仲間', 'act_connection': 'ゲーム仲間探し', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    69: {'all_key': 'オタ話する', 'act': 'オタ話する', 'act_noun': 'オタ友探し', 'eng': 'geek_friends', 'act_target': 'オタ友',
         'act_connection': 'オタ友探し', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    70: {'all_key': '飲み友達を作る', 'act': '飲み友達を作る', 'act_noun': '飲み友達探し', 'eng': 'drinking_friend',
         'act_target': '飲み友達', 'act_connection': '飲み友達探し', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    71: {'all_key': '親友を作る', 'act': '親友を作る', 'act_noun': '親友探し', 'eng': 'close_friend', 'act_target': '親友',
         'act_connection': '親友探し', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    72: {'all_key': '恋バナする', 'act': '恋バナする', 'act_noun': '恋バナ', 'eng': 'love_flower', 'act_target': '恋バナ相手',
         'act_connection': '恋バナ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    73: {'all_key': '会話する', 'act': '会話する', 'act_noun': '会話', 'eng': 'conversation', 'act_target': '話し相手',
         'act_connection': '会話', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    74: {'all_key': '雑談する', 'act': '雑談する', 'act_noun': '雑談', 'eng': 'chat', 'act_target': '雑談相手',
         'act_connection': '雑談', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    75: {'all_key': '男友達を作る', 'act': '男友達を作る', 'act_noun': '男友達探し', 'eng': 'friend_search', 'act_target': '男友達',
         'act_connection': '男友達探し', 'a_sex': 'w', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    76: {'all_key': '彼氏を作る', 'act': '彼氏を作る', 'act_noun': '彼氏探し', 'eng': 'boyfriend', 'act_target': '彼氏',
         'act_connection': '彼氏探し', 'a_sex': 'w', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    77: {'all_key': '寝取る', 'act': '寝取る', 'act_noun': '寝取り', 'eng': 'cuckold', 'act_target': '寝取り相手',
         'act_connection': '寝取り', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'を', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    78: {'all_key': '寝取られる', 'act': '寝取られる', 'act_noun': 'ネトラレ', 'eng': 'netrale', 'act_target': 'ネトラレ対象',
         'act_connection': 'ネトラレ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    79: {'all_key': '再婚する', 'act': '再婚する', 'act_noun': '再婚', 'eng': 'reigning', 'act_target': '再婚相手',
         'act_connection': '再婚', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'て', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    80: {'all_key': '復縁する', 'act': '復縁する', 'act_noun': '復縁', 'eng': 'recovery', 'act_target': '元の恋人',
         'act_connection': '復縁', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'て', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    81: {'all_key': 'マッチングする', 'act': 'マッチングする', 'act_noun': 'マッチング', 'eng': 'matching',
         'act_target': 'マッチング相手', 'act_connection': 'マッチング', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    82: {'all_key': '同棲する', 'act': '同棲する', 'act_noun': '同棲', 'eng': 'homogeneous', 'act_target': '同棲相手',
         'act_connection': '同棲', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    83: {'all_key': '婚外恋愛する', 'act': '婚外恋愛する', 'act_noun': '婚外恋愛', 'eng': 'marrying_love',
         'act_target': '婚外恋愛の相手', 'act_connection': '婚外恋愛', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    84: {'all_key': 'コスプレセックスする', 'act': 'コスプレセックスする', 'act_noun': 'コスプレセックス', 'eng': 'cosplay_sex',
         'act_target': 'コスプレセックス好き', 'act_connection': 'コスプレセックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    85: {'all_key': 'デートする', 'act': 'デートする', 'act_noun': 'デート', 'eng': 'dating2', 'act_target': 'デート相手',
         'act_connection': 'デート', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    86: {'all_key': '面接する', 'act': '面接する', 'act_noun': '出会い面接', 'eng': 'encounter_interview',
         'act_target': '面接相手', 'act_connection': '出会い面接', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    87: {'all_key': '待ち合わせする', 'act': '待ち合わせする', 'act_noun': '待ち合わせ', 'eng': 'meeting', 'act_target': '待ち合わせ相手',
         'act_connection': '待ち合わせ', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    88: {'all_key': '即ヤリする', 'act': '即ヤリする', 'act_noun': '即ヤリ', 'eng': 'immediate', 'act_target': '即ヤリできる異性',
         'act_connection': '即ヤリ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    89: {'all_key': 'ヤリモクで会う', 'act': 'ヤリモクで会う', 'act_noun': 'ヤリモク', 'eng': 'yarimok', 'act_target': 'ヤリモクの対象',
         'act_connection': 'ヤリモク', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    90: {'all_key': 'ネトナンする', 'act': 'ネトナンする', 'act_noun': 'ネットナンパ', 'eng': 'netnampa',
         'act_target': 'ネットナンパのターゲット', 'act_connection': 'ネットナンパ', 'a_sex': 'a', 'ignore_a': ['sf'],
         'obj_p': 'と', 'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    91: {'all_key': 'オンラインデートする', 'act': 'オンラインデートする', 'act_noun': 'オンラインデート', 'eng': 'online_date',
         'act_target': 'オンラインデート相手', 'act_connection': 'オンラインデート', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    92: {'all_key': 'アブノーマルセックスする', 'act': 'アブノーマルセックスする', 'act_noun': 'アブノーマルセックス', 'eng': 'abs_normal_sex',
         'act_target': 'アブノーマル女子', 'act_connection': 'アブノーマルセックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    93: {'all_key': 'お持ち帰りする', 'act': 'お持ち帰りする', 'act_noun': 'お持ち帰り', 'eng': 'takeaway',
         'act_target': 'お持ち帰り相手', 'act_connection': 'お持ち帰り', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    94: {'all_key': '朝チュンする', 'act': '朝チュンする', 'act_noun': '朝チュン', 'eng': 'chun', 'act_target': '朝チュン相手',
         'act_connection': '朝チュン', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    95: {'all_key': '行きずりセックスする', 'act': '行きずりセックスする', 'act_noun': '行きずりセックス', 'eng': 'sliding_sex',
         'act_target': '行きずりセックス相手', 'act_connection': '行きずりセックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    96: {'all_key': 'ナンパする', 'act': 'ナンパする', 'act_noun': 'ナンパ', 'eng': 'pear', 'act_target': 'ナンパターゲット',
         'act_connection': 'ナンパ', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    97: {'all_key': 'やり捨てする', 'act': 'やり捨てする', 'act_noun': 'やり捨て', 'eng': 'discard', 'act_target': 'やり捨て相手',
         'act_connection': 'やり捨て', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 1},
    98: {'all_key': 'お泊まりセックスする', 'act': 'お泊まりセックスする', 'act_noun': 'お泊まりセックス', 'eng': 'stay_sex',
         'act_target': 'お泊まりセックス相手', 'act_connection': 'お泊まりセックス', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
         'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    99: {'all_key': '通話する', 'act': '通話する', 'act_noun': '通話', 'eng': 'call', 'act_target': '通話の相手',
         'act_connection': '通話', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
         '2act_w': '', '2act_noun': '', 'a_ad': 3},
    100: {'all_key': 'サイト内電話する', 'act': 'サイト内電話する', 'act_noun': 'サイト内電話', 'eng': 'site_call',
          'act_target': 'サイト内電話の対象', 'act_connection': 'サイト内電話', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    101: {'all_key': 'アナルセックスする', 'act': 'アナルセックスする', 'act_noun': 'AF', 'eng': 'anal_fuck',
          'act_target': 'アナル好き女子', 'act_connection': 'AF', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    102: {'all_key': '搾精してもらう', 'act': '搾精してもらう', 'act_noun': '搾精', 'eng': 'squeeze', 'act_target': '搾精女子',
          'act_connection': '搾精', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 1},
    103: {'all_key': '緊縛プレイする', 'act': '緊縛プレイする', 'act_noun': '緊縛プレイ', 'eng': 'bdsd_play',
          'act_target': '緊縛プレイ好き', 'act_connection': '緊縛プレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    104: {'all_key': '羞恥プレイする', 'act': '羞恥プレイする', 'act_noun': '羞恥プレイ', 'eng': 'shame_play',
          'act_target': '羞恥プレイ好き', 'act_connection': '羞恥プレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    105: {'all_key': '目隠しセックスする', 'act': '目隠しセックスする', 'act_noun': '目隠しプレイ', 'eng': 'blindfold_play',
          'act_target': '目隠し好き', 'act_connection': '目隠しプレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    106: {'all_key': '赤ちゃんプレイする', 'act': '赤ちゃんプレイする', 'act_noun': '赤ちゃんプレイ', 'eng': 'baby_play',
          'act_target': '赤ちゃんプレイ好き', 'act_connection': '赤ちゃんプレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    107: {'all_key': 'ラインする', 'act': 'ラインする', 'act_noun': 'ライントーク', 'eng': 'line', 'act_target': 'ライントーク相手',
          'act_connection': 'ライントーク', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 3},
    108: {'all_key': '連絡先交換する', 'act': '連絡先交換する', 'act_noun': '連絡先交換', 'eng': 'contact',
          'act_target': '連絡先交換の相手', 'act_connection': '連絡先交換', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    109: {'all_key': 'ラインID交換する', 'act': 'ラインID交換する', 'act_noun': 'ラインID交換', 'eng': 'line_id',
          'act_target': 'ラインID交換相手', 'act_connection': 'ラインID交換', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    110: {'all_key': 'メールアドレスを聞く', 'act': 'メールアドレスを聞く', 'act_noun': 'メアド交換', 'eng': 'mail_address',
          'act_target': 'メアド交換の相手', 'act_connection': 'メアド交換', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    111: {'all_key': 'アナル舐めしてもらう', 'act': 'アナル舐めしてもらう', 'act_noun': 'アナル舐め', 'eng': 'anal_licking',
          'act_target': 'アナル舐めOK女子', 'act_connection': 'アナル舐め', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    112: {'all_key': 'しゃぶってもらう', 'act': 'しゃぶってもらう', 'act_noun': 'おしゃぶり', 'eng': 'pacifier',
          'act_target': 'おしゃぶり好き', 'act_connection': 'おしゃぶり', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    113: {'all_key': '露出プレイする', 'act': '露出プレイする', 'act_noun': '露出プレイ', 'eng': 'exposure_play',
          'act_target': '露出プレイ好き', 'act_connection': '露出プレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    114: {'all_key': '焦らしプレイする', 'act': '焦らしプレイする', 'act_noun': '焦らしプレイ', 'eng': 'fit_play',
          'act_target': '焦らされ好き', 'act_connection': '焦らしプレイ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    115: {'all_key': '言葉責めする', 'act': '言葉責めする', 'act_noun': '言葉責め', 'eng': 'words_blame',
          'act_target': '言葉責め好き', 'act_connection': '言葉責め', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    116: {'all_key': 'イラマチオしてもらう', 'act': 'イラマチオしてもらう', 'act_noun': 'イラマチオ', 'eng': 'iramatio',
          'act_target': 'イラマチオOK女子', 'act_connection': 'イラマチオ', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    117: {'all_key': '添い寝する', 'act': '添い寝する', 'act_noun': '添い寝', 'eng': 'sleeping', 'act_target': '添い寝好き',
          'act_connection': '添い寝', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 1},
    118: {'all_key': 'ソフレを作る', 'act': 'ソフレを作る', 'act_noun': 'ソフレ探し', 'eng': 'softle_search',
          'act_target': 'ソフレ', 'act_connection': 'ソフレ探し', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    119: {'all_key': 'キスフレを作る', 'act': 'キスフレを作る', 'act_noun': 'キスフレ探し', 'eng': 'search_for_kiss',
          'act_target': 'キスフレ', 'act_connection': 'キスフレ探し', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    120: {'all_key': '遠距離恋愛する', 'act': '遠距離恋愛する', 'act_noun': '遠距離恋愛', 'eng': 'long_distance_love',
          'act_target': '遠距離の恋人', 'act_connection': '遠距離恋愛', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    121: {'all_key': '本命交際する', 'act': '本命交際する', 'act_noun': '本命交際', 'eng': 'lighthing', 'act_target': '本命の恋人',
          'act_connection': '本命交際', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 3},
    122: {'all_key': 'メール交換する', 'act': 'メール交換する', 'act_noun': 'メール交換', 'eng': 'mail_exchange',
          'act_target': 'メール友達', 'act_connection': 'メール交換', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    123: {'all_key': '彼氏募集する', 'act': '彼氏募集する', 'act_noun': '彼氏募集', 'eng': 'recruit_boyfriend',
          'act_target': '彼氏', 'act_connection': '彼氏募集', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    124: {'all_key': '彼女募集する', 'act': '彼女募集する', 'act_noun': '彼女募集', 'eng': 'recruit_girlfriend',
          'act_target': '彼女', 'act_connection': '彼女募集', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 3},
    125: {'all_key': '逆援交する', 'act': '逆援交する', 'act_noun': '逆援交', 'eng': 'backing', 'act_target': '逆援交の相手',
          'act_connection': '逆援交', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 0},
    126: {'all_key': '車内フェラしてもらう', 'act': '車内フェラしてもらう', 'act_noun': '車内F', 'eng': 'in_the_car',
          'act_target': '車内F好き', 'act_connection': '車内F', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'に',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    127: {'all_key': 'F割りする', 'act': 'F割りする', 'act_noun': 'フェラ割り', 'eng': 'blow_off', 'act_target': 'フェラ割り募集女子',
          'act_connection': 'フェラ割り', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 0},
    128: {'all_key': '大人の関係になる', 'act': '大人の関係になる', 'act_noun': '大人の関係', 'eng': 'adult_relationship',
          'act_target': '大人の関係の相手', 'act_connection': '大人の関係', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    129: {'all_key': '大人の交際をする', 'act': '大人の交際をする', 'act_noun': '大人の交際', 'eng': 'adult_dating',
          'act_target': '大人の交際の相手', 'act_connection': '大人の交際', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    130: {'all_key': '愛人を作る', 'act': '愛人を作る', 'act_noun': '愛人作り', 'eng': 'lovers', 'act_target': '愛人',
          'act_connection': '愛人関係', 'a_sex': 'a', 'ignore_a': ['sf'], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 0},
    131: {'all_key': '即会いする', 'act': '即会いする', 'act_noun': '即会い', 'eng': 'promise', 'act_target': '即会いできる人',
          'act_connection': '即会い', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 1},
    132: {'all_key': '秘密の関係になる', 'act': '秘密の関係になる', 'act_noun': '秘密の関係', 'eng': 'secret_relationship',
          'act_target': '秘密の恋人', 'act_connection': '秘密の関係', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    133: {'all_key': '秘密の交際をする', 'act': '秘密の交際をする', 'act_noun': '秘密の交際', 'eng': 'secret_relationship2',
          'act_target': '秘密の交際相手', 'act_connection': '秘密の交際', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    134: {'all_key': '割り切った交際をする', 'act': '割り切った交際をする', 'act_noun': '割り切り交際', 'eng': 'division2',
          'act_target': '割り切った相手', 'act_connection': '割り切り交際', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    135: {'all_key': '大人の恋愛をする', 'act': '大人の恋愛をする', 'act_noun': '大人の恋愛', 'eng': 'adult_love',
          'act_target': '大人の恋人', 'act_connection': '大人の恋愛', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    136: {'all_key': 'ヤリまくる', 'act': 'ヤリまくる', 'act_noun': 'ヤリまくり', 'eng': 'irregular', 'act_target': 'ヤリまくれる相手',
          'act_connection': 'ヤリまくり', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 1},
    137: {'all_key': '定期で会う', 'act': '定期で会う', 'act_noun': '定期の交際', 'eng': 'periodic_relationship',
          'act_target': '定期さん', 'act_connection': '定期', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と',
          'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1},
    138: {'all_key': 'カラオケに行く', 'act': 'カラオケに行く', 'act_noun': 'カラオケ', 'eng': 'karaoke', 'act_target': 'カラオケ相手',
          'act_connection': 'カラオケ仲間', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 3},
    139: {'all_key': '不貞行為する', 'act': '不貞行為する', 'act_noun': '不貞行為', 'eng': 'unfair_act', 'act_target': '不貞の相手',
          'act_connection': '不貞関係', 'a_sex': 'a', 'ignore_a': [], 'obj_p': 'と', 'act_noun_flag': False,
          '2act_w': '', '2act_noun': '', 'a_ad': 1},
    140: {'all_key': 'お掃除フェラしてもらう', 'act': 'お掃除フェラしてもらう', 'act_noun': 'お掃除フェラ', 'eng': 'cleaning',
          'act_target': 'お掃除フェラしてくれる<!--woman-->', 'act_connection': 'お掃除フェラ関係', 'a_sex': 'a', 'ignore_a': [],
          'obj_p': 'に', 'act_noun_flag': False, '2act_w': '', '2act_noun': '', 'a_ad': 1}}

adj_dict = {
    0: {'a_adj': 'ワクワクメールで', 'site': 'wk'},
    1: {'a_adj': 'ハッピーメールで', 'site': 'hm'},
    2: {'a_adj': 'PCMAXで', 'site': 'pc'},
    3: {'a_adj': 'Jメールで', 'site': 'mj'}
}

# act_dict = {x: act_dict[x] for x in act_dict if 'sf' not in act_dict[x]['ignore_a']}

if len(act_dict) >= len(adj_dict):
    key_data1 = act_dict
    key_data2 = adj_dict
    ud_flag = ['key_a', 'key_b']
else:
    key_data1 = adj_dict
    key_data2 = act_dict
    ud_flag = ['key_b', 'key_a']
result_list = {}
used_list = []
i = 0
for id1 in key_data1:
    if i < len(key_data2):
        pass
    else:
        i = 0
    result_list[id1] = key_data1[id1] | key_data2[i] | {'type': 'mix_act',
                                                        'all_key': key_data2[i]['a_adj'] + key_data1[id1]['act']}
    used_list.append(['{}_{}'.format(ud_flag[0], id1), '{}_{}'.format(ud_flag[1], i)])
    i += 1
key_dict = result_list


# print(result_list)
# print(used_list)
