keyword_dict = {
    0: {'all_key': 'イケメン', 'obj_key': 'イケメン', 'obj': 'イケメン', 'eng': 'good-looking_guy', 'o_adj': 'かっこいい', 'obj_p': 'の',
        'o_cat': 'l', 'o_ms': 's', 'o_age': 'n', 'look': True, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    1: {'all_key': '元カレ', 'obj_key': '元カレ', 'obj': '元カレ', 'eng': 'ex-boyfriend', 'o_adj': '失恋した', 'obj_p': 'の',
        'o_cat': 's', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    2: {'all_key': '同僚', 'obj_key': '同僚', 'obj': '同僚', 'eng': 'colleague', 'o_adj': '気になる', 'obj_p': 'の', 'o_cat': 's',
        'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    3: {'all_key': '外国人', 'obj_key': '外国人', 'obj': '外国人', 'eng': 'alien', 'o_adj': 'イケてる', 'obj_p': 'の', 'o_cat': 'c',
        'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    4: {'all_key': '上司', 'obj_key': '上司', 'obj': '上司', 'eng': 'boss', 'o_adj': 'ダンディーな', 'obj_p': 'の', 'o_cat': 's',
        'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    5: {'all_key': '外人', 'obj_key': '外人', 'obj': '外人', 'eng': 'alien2', 'o_adj': 'ダンディーな', 'obj_p': 'の', 'o_cat': 'c',
        'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    6: {'all_key': '医者', 'obj_key': '医者', 'obj': '医者', 'eng': 'doctor', 'o_adj': '優秀な', 'obj_p': 'の', 'o_cat': 'j',
        'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    7: {'all_key': '先輩', 'obj_key': '先輩', 'obj': '先輩', 'eng': 'elder', 'o_adj': '親切な', 'obj_p': 'の', 'o_cat': 's',
        'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    8: {'all_key': 'バンドマン', 'obj_key': 'バンドマン', 'obj': 'バンドマン', 'eng': 'bandsman', 'o_adj': 'モテる', 'obj_p': 'の',
        'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    9: {'all_key': '消防士', 'obj_key': '消防士', 'obj': '消防士', 'eng': 'fireman', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'j',
        'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    10: {'all_key': '未成年', 'obj_key': '未成年', 'obj': '未成年', 'eng': 'under_age', 'o_adj': '', 'obj_p': 'の', 'o_cat': 's',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    11: {'all_key': 'マッチョ', 'obj_key': 'マッチョ', 'obj': 'マッチョ男子', 'eng': 'machismo', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    12: {'all_key': '医師', 'obj_key': '医師', 'obj': '医師', 'eng': 'doctor2', 'o_adj': '頭がいい', 'obj_p': 'の', 'o_cat': 'j',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    13: {'all_key': 'ヤリチン', 'obj_key': 'ヤリチン', 'obj': 'ヤリチン', 'eng': 'man_whore', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    14: {'all_key': '職場の先輩', 'obj_key': '職場の先輩', 'obj': '職場の先輩', 'eng': 'office_elder', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 's', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    15: {'all_key': '経営者', 'obj_key': '経営者', 'obj': '経営者', 'eng': 'manager', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'j',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    16: {'all_key': '研修医', 'obj_key': '研修医', 'obj': '研修医', 'eng': 'resident', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'j',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    17: {'all_key': '自衛隊', 'obj_key': '自衛隊', 'obj': '自衛隊員', 'eng': 'self-defense_forces', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    18: {'all_key': '独身男性', 'obj_key': '独身男性', 'obj': '独身男性', 'eng': 'single', 'o_adj': '', 'obj_p': 'の', 'o_cat': 's',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    19: {'all_key': '公務員', 'obj_key': '公務員', 'obj': '公務員', 'eng': 'public_service_worker', 'o_adj': '安定した',
         'obj_p': 'の', 'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    20: {'all_key': '高学歴', 'obj_key': '高学歴', 'obj': '高学歴男子', 'eng': 'higher_education', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    21: {'all_key': '自慢できる', 'obj_key': '自慢できる', 'obj': '自慢できる男性', 'eng': 'proud', 'o_adj': '', 'obj_p': 'no',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    22: {'all_key': '都合のいい', 'obj_key': '都合のいい', 'obj': '都合のいい男性', 'eng': 'convenient', 'o_adj': '', 'obj_p': 'no',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    23: {'all_key': '飽きない', 'obj_key': '飽きない', 'obj': '飽きない男性', 'eng': 'not_tired', 'o_adj': '', 'obj_p': 'no',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    24: {'all_key': '営業マン', 'obj_key': '営業マン', 'obj': '営業マン', 'eng': 'salesman', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    25: {'all_key': 'お金持ち', 'obj_key': 'お金持ち', 'obj': 'お金持ち男性', 'eng': 'rich', 'o_adj': '', 'obj_p': 'の', 'o_cat': 's',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    26: {'all_key': '芸能人', 'obj_key': '芸能人', 'obj': '芸能人', 'eng': 'entertainer', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    27: {'all_key': '警察官', 'obj_key': '警察官', 'obj': '警察官', 'eng': 'policeman', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'j',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    28: {'all_key': 'アスリート', 'obj_key': 'アスリート', 'obj': 'アスリート', 'eng': 'athlete', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    29: {'all_key': '優しい', 'obj_key': '優しい', 'obj': '優しい男性', 'eng': 'gentle', 'o_adj': '', 'obj_p': 'no', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    30: {'all_key': '尽くしてくれる', 'obj_key': '尽くしてくれる', 'obj': '尽くしてくれる男性', 'eng': 'devoted', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    31: {'all_key': 'セックスが上手い', 'obj_key': 'セックスが上手い', 'obj': 'セックスが上手い男性', 'eng': 'nice_sex', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 1},
    32: {'all_key': 'マメな', 'obj_key': 'マメな', 'obj': 'マメな男性', 'eng': 'methodical', 'o_adj': '', 'obj_p': 'no',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    33: {'all_key': '御曹司', 'obj_key': '御曹司', 'obj': '御曹司', 'eng': 'son_of_noble_family', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    34: {'all_key': '社長', 'obj_key': '社長', 'obj': '社長', 'eng': 'president', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'j',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    35: {'all_key': '海上保安庁', 'obj_key': '海上保安庁', 'obj': '海上保安官', 'eng': 'coast_guard', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    36: {'all_key': 'パイロット', 'obj_key': 'パイロット', 'obj': 'パイロット', 'eng': 'pilot', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    37: {'all_key': '弁護士', 'obj_key': '弁護士', 'obj': '弁護士', 'eng': 'lawyar', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'j',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    38: {'all_key': '政治家', 'obj_key': '政治家', 'obj': '政治家', 'eng': 'atatesman', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'j',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    39: {'all_key': '医大生', 'obj_key': '医大生', 'obj': '医大生', 'eng': 'medical_student', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'j', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    40: {'all_key': 'エリート', 'obj_key': 'エリート', 'obj': 'エリート男性', 'eng': 'elite', 'o_adj': '', 'obj_p': 'の', 'o_cat': 's',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    41: {'all_key': '東大卒', 'obj_key': '東大卒', 'obj': '東大卒男性', 'eng': 'tokyo_university', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 's', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    42: {'all_key': '高身長', 'obj_key': '高身長', 'obj': '高身長男性', 'eng': 'tall', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    43: {'all_key': 'おじさん', 'obj_key': 'おじさん', 'obj': 'おじさん', 'eng': 'uncle', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'o', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    44: {'all_key': '年上', 'obj_key': '年上', 'obj': '年上男性', 'eng': 'older', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'o', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    45: {'all_key': '中年', 'obj_key': '中年', 'obj': '中年男性', 'eng': 'middle_age', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'o', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    46: {'all_key': '真面目な', 'obj_key': '真面目な', 'obj': '真面目な男性', 'eng': 'serious', 'o_adj': '', 'obj_p': 'no',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    47: {'all_key': 'O型', 'obj_key': 'O型', 'obj': 'O型男性', 'eng': 'type_o', 'o_adj': 'おおらかな', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    48: {'all_key': 'B型', 'obj_key': 'B型', 'obj': 'B型男性', 'eng': 'type_b', 'o_adj': '積極的な', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    49: {'all_key': 'AB型', 'obj_key': 'AB型', 'obj': 'AB型男性', 'eng': 'type_ab', 'o_adj': '個性的な', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    50: {'all_key': 'A型', 'obj_key': 'A型', 'obj': 'A型男性', 'eng': 'type_a', 'o_adj': '真面目な', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    51: {'all_key': 'サラリーマン', 'obj_key': 'サラリーマン', 'obj': 'サラリーマン', 'eng': 'salary_man', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    52: {'all_key': '薬剤師', 'obj_key': '薬剤師', 'obj': '薬剤師', 'eng': 'pharmacist', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    53: {'all_key': '理学療法士', 'obj_key': '理学療法士', 'obj': '理学療法士', 'eng': 'physical_therapist', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    54: {'all_key': '税理士', 'obj_key': '税理士', 'obj': '税理士', 'eng': 'tax_accountant', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    55: {'all_key': '教員', 'obj_key': '教員', 'obj': '教員', 'eng': 'teacher', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    56: {'all_key': 'エンジニア', 'obj_key': 'エンジニア', 'obj': 'エンジニア', 'eng': 'engineer', 'o_adj': 'IT系の', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    57: {'all_key': '建築士', 'obj_key': '建築士', 'obj': '建築士', 'eng': 'architect', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    58: {'all_key': 'クリエイター', 'obj_key': 'クリエイター', 'obj': 'クリエイター', 'eng': 'creator', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    59: {'all_key': 'IT社長', 'obj_key': 'IT社長', 'obj': 'IT社長', 'eng': 'it_president', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    60: {'all_key': '商社マン', 'obj_key': '商社マン', 'obj': '商社マン', 'eng': 'commercial_man', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    61: {'all_key': '銀行員', 'obj_key': '銀行員', 'obj': '銀行員', 'eng': 'banker', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    62: {'all_key': '金融マン', 'obj_key': '金融マン', 'obj': '金融マン', 'eng': 'financial_man', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    63: {'all_key': 'セクシー男優', 'obj_key': 'セクシー男優', 'obj': 'セクシー男優', 'eng': 'sexy_actor', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    64: {'all_key': 'AV男優', 'obj_key': 'AV男優', 'obj': 'AV男優', 'eng': 'av_actor', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    65: {'all_key': 'スポーツ選手', 'obj_key': 'スポーツ選手', 'obj': 'スポーツ選手', 'eng': 'athlete2', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    66: {'all_key': '自衛官', 'obj_key': '自衛官', 'obj': '自衛官', 'eng': 'self-defense_officer', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    67: {'all_key': 'ホスト', 'obj_key': 'ホスト', 'obj': 'ホスト', 'eng': 'host', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    68: {'all_key': 'ガテン系', 'obj_key': 'ガテン系', 'obj': 'ガテン系', 'eng': 'physical-labor', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    69: {'all_key': '大工', 'obj_key': '大工', 'obj': '大工', 'eng': 'carpenter', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    70: {'all_key': '土木作業員', 'obj_key': '土木作業員', 'obj': '土木作業員', 'eng': 'civil_engineering_worker', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    71: {'all_key': 'ジムインストラクター', 'obj_key': 'ジムインストラクター', 'obj': 'ジムインストラクター', 'eng': 'gym_instructor', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    72: {'all_key': '美容師', 'obj_key': '美容師', 'obj': '美容師', 'eng': 'hairdresser', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    73: {'all_key': 'IT関係', 'obj_key': 'IT関係', 'obj': 'IT関係', 'eng': 'it_relation', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    74: {'all_key': '外資系', 'obj_key': '外資系', 'obj': '外資系', 'eng': 'foreign_owned', 'o_adj': '英語ペラペラの', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    75: {'all_key': '実業家', 'obj_key': '実業家', 'obj': '実業家', 'eng': 'businessman', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    76: {'all_key': 'アパレル関係', 'obj_key': 'アパレル関係', 'obj': 'アパレル関係', 'eng': 'apparel', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    77: {'all_key': '料理人', 'obj_key': '料理人', 'obj': '料理人', 'eng': 'cook', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    78: {'all_key': '広告代理店', 'obj_key': '広告代理店', 'obj': '広告代理店社員', 'eng': 'advertising_agency', 'o_adj': 'センスのいい',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    79: {'all_key': 'メーカー社員', 'obj_key': 'メーカー社員', 'obj': 'メーカー社員', 'eng': 'manufacturer_employee', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    80: {'all_key': '公認会計士', 'obj_key': '公認会計士', 'obj': '公認会計士', 'eng': 'certified_public_accountant', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    81: {'all_key': 'テレビ関係', 'obj_key': 'テレビ関係', 'obj': 'テレビマン', 'eng': 'television_relationship', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    82: {'all_key': 'マスコミ関係', 'obj_key': 'マスコミ関係', 'obj': 'マスコミ社員', 'eng': 'masquietual_relations', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    83: {'all_key': '国家公務員', 'obj_key': '国家公務員', 'obj': '国家公務員', 'eng': 'government_official', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    84: {'all_key': '地方公務員', 'obj_key': '地方公務員', 'obj': '地方公務員', 'eng': 'local_government_employee', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    85: {'all_key': 'キャリア官僚', 'obj_key': 'キャリア官僚', 'obj': 'キャリア官僚', 'eng': 'carrier_bureaucracy', 'o_adj': '',
         'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
         'ad': 3},
    86: {'all_key': '教師', 'obj_key': '教師', 'obj': '教師', 'eng': 'teacher2', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    87: {'all_key': 'プログラマー', 'obj_key': 'プログラマー', 'obj': 'プログラマー', 'eng': 'programmer', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    88: {'all_key': '大企業', 'obj_key': '大企業', 'obj': '大企業社員', 'eng': 'large_companies', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    89: {'all_key': 'パティシエ', 'obj_key': 'パティシエ', 'obj': 'パティシエ', 'eng': 'patisier', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    90: {'all_key': '整体師', 'obj_key': '整体師', 'obj': '整体師', 'eng': 'chiropractor', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    91: {'all_key': 'マッサージ師', 'obj_key': 'マッサージ師', 'obj': 'マッサージ師', 'eng': 'masseur', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    92: {'all_key': 'シェフ', 'obj_key': 'シェフ', 'obj': 'シェフ', 'eng': 'chef', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    93: {'all_key': '介護士', 'obj_key': '介護士', 'obj': '介護士', 'eng': 'carer', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    94: {'all_key': 'バーテンダー', 'obj_key': 'バーテンダー', 'obj': 'バーテンダー', 'eng': 'bartender', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    95: {'all_key': 'お笑い芸人', 'obj_key': 'お笑い芸人', 'obj': 'お笑い芸人', 'eng': 'comedian', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    96: {'all_key': '漁師', 'obj_key': '漁師', 'obj': '漁師', 'eng': 'fisherman', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    97: {'all_key': '農家', 'obj_key': '農家', 'obj': '農家', 'eng': 'farmer', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    98: {'all_key': 'お坊さん', 'obj_key': 'お坊さん', 'obj': 'お坊さん', 'eng': 'monk', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
         'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    99: {'all_key': 'YouTuber', 'obj_key': 'YouTuber', 'obj': 'YouTuber', 'eng': 'youtuber', 'o_adj': '', 'obj_p': 'の',
         'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    100: {'all_key': '既婚者', 'obj_key': '既婚者', 'obj': '既婚者男性', 'eng': 'married', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 'm', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 0},
    101: {'all_key': '権力者', 'obj_key': '権力者', 'obj': '権力者', 'eng': 'authority', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    102: {'all_key': '大学生', 'obj_key': '大学生', 'obj': '大学生', 'eng': 'university_student', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    103: {'all_key': '東大生', 'obj_key': '東大生', 'obj': '東大生', 'eng': 'tokyo_university_student', 'o_adj': '',
          'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj',
          'ad': 1},
    104: {'all_key': '慶応', 'obj_key': '慶応', 'obj': '慶応大生', 'eng': 'keio_university', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    105: {'all_key': '早稲田', 'obj_key': '早稲田', 'obj': '早稲田大生', 'eng': 'waseda_university', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    106: {'all_key': '癒し系', 'obj_key': '癒し系', 'obj': '癒し系男子', 'eng': 'healing', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    107: {'all_key': 'オラオラ系', 'obj_key': 'オラオラ系', 'obj': 'オラオラ系男性', 'eng': 'aggressive', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    108: {'all_key': '王子様', 'obj_key': '王子様', 'obj': '王子様', 'eng': 'prince', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    109: {'all_key': 'オタク', 'obj_key': 'オタク', 'obj': 'オタク', 'eng': 'geek', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    110: {'all_key': '筋肉質', 'obj_key': '筋肉質', 'obj': '筋肉質男子', 'eng': 'muscular', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    111: {'all_key': '細マッチョ', 'obj_key': '細マッチョ', 'obj': '細マッチョ男子', 'eng': 'thin_maccho', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    112: {'all_key': 'ジャニーズ系', 'obj_key': 'ジャニーズ系', 'obj': 'ジャニーズ系男子', 'eng': 'johnnys', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    113: {'all_key': 'イケオジ', 'obj_key': 'イケオジ', 'obj': 'イケオジ', 'eng': 'good_muture_man', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    114: {'all_key': 'おじ様', 'obj_key': 'おじ様', 'obj': 'おじ様', 'eng': 'muture_man', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 1},
    115: {'all_key': 'ダンディー', 'obj_key': 'ダンディー', 'obj': 'ダンディー男性', 'eng': 'dundee', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': False, 'o_sex': 'm', 'type': 'only_obj', 'ad': 3},
    # 2021/9/8 追加
    116: {'all_key': '次男', 'obj_key': '次男', 'obj': '次男', 'eng': 'second_son', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    117: {'all_key': '長男', 'obj_key': '長男', 'obj': '長男', 'eng': 'eldest_son', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    118: {'all_key': '草食系', 'obj_key': '草食系', 'obj': '草食系男子', 'eng': 'herbivorous_system', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    119: {'all_key': '肉食系', 'obj_key': '肉食系', 'obj': '肉食系男子', 'eng': 'carnivorous_system', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    120: {'all_key': '醤油顔', 'obj_key': '醤油顔', 'obj': '醤油顔男性', 'eng': 'soy_sauce_face', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    121: {'all_key': 'ソース顔', 'obj_key': 'ソース顔', 'obj': 'ソース顔男子', 'eng': 'sauce_face', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    122: {'all_key': '家庭的', 'obj_key': '家庭的', 'obj': '家庭的な男性', 'eng': 'homeborne', 'o_adj': '', 'obj_p': 'な',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    123: {'all_key': '地方在住', 'obj_key': '地方在住', 'obj': '地方在住男子', 'eng': 'local_residence', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    124: {'all_key': '運命', 'obj_key': '運命', 'obj': '運命の人', 'eng': 'fate', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    125: {'all_key': '童貞', 'obj_key': '童貞', 'obj': '童貞', 'eng': 'virginity', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '1', 'type': 'only_obj'},
    126: {'all_key': 'プロ野球選手', 'obj_key': 'プロ野球選手', 'obj': 'プロ野球選手', 'eng': 'professional_baseball_player', 'o_adj': '',
          'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3',
          'type': 'only_obj'},
    127: {'all_key': 'サッカー選手', 'obj_key': 'サッカー選手', 'obj': 'サッカー選手', 'eng': 'soccer_player', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    128: {'all_key': 'Jリーガー', 'obj_key': 'Jリーガー', 'obj': 'Jリーガー', 'eng': 'j_liger', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    129: {'all_key': 'プロ棋士', 'obj_key': 'プロ棋士', 'obj': 'プロ棋士', 'eng': 'professional', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    130: {'all_key': '巨根', 'obj_key': '巨根', 'obj': 'デカチン男子', 'eng': 'big_dick', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '1', 'type': 'only_obj'},
    131: {'all_key': 'フェミニスト', 'obj_key': 'フェミニスト', 'obj': 'フェミ男', 'eng': 'feminist', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    132: {'all_key': '博士', 'obj_key': '博士', 'obj': 'ドクター男子', 'eng': 'doctor3', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's',
          'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    133: {'all_key': '性格がいい', 'obj_key': '性格がいい', 'obj': '性格がいい男性', 'eng': 'good_character', 'o_adj': '', 'obj_p': 'no',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    134: {'all_key': 'ベンチャー勤務', 'obj_key': 'ベンチャー勤務', 'obj': 'ベンチャー社員', 'eng': 'venture', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    135: {'all_key': '一途', 'obj_key': '一途', 'obj': '一途男子', 'eng': 'one_way', 'o_adj': '', 'obj_p': 'な', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    136: {'all_key': 'アニメ好き', 'obj_key': 'アニメ好き', 'obj': 'アニオタ男子', 'eng': 'animation', 'o_adj': '', 'obj_p': 'な',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    137: {'all_key': 'お坊ちゃん', 'obj_key': 'お坊ちゃん', 'obj': 'お坊ちゃん', 'eng': 'boy', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    138: {'all_key': '医療職', 'obj_key': '医療職', 'obj': '医療従事者', 'eng': 'medical_office', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    139: {'all_key': 'アウトドア好き', 'obj_key': 'アウトドア好き', 'obj': 'アウトドア男子', 'eng': 'i_like_outdoor', 'o_adj': '',
          'obj_p': 'な', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3',
          'type': 'only_obj'},
    140: {'all_key': 'サーファー', 'obj_key': 'サーファー', 'obj': 'サーファー', 'eng': 'surfer', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    141: {'all_key': '中国人', 'obj_key': '中国人', 'obj': '中国人男性', 'eng': 'chinese', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    142: {'all_key': '韓国人', 'obj_key': '韓国人', 'obj': '韓国人男性', 'eng': 'korean', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    143: {'all_key': '白人', 'obj_key': '白人', 'obj': '白人男性', 'eng': 'caucasian', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    144: {'all_key': 'アフリカ系アメリカ人', 'obj_key': 'アフリカ系アメリカ人', 'obj': 'アフリカ系アメリカ人男性', 'eng': 'african_american',
          'o_adj': '', 'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3',
          'type': 'only_obj'},
    145: {'all_key': '美少年', 'obj_key': '美少年', 'obj': '美少年', 'eng': 'beautiful_boy', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    146: {'all_key': '経験豊富', 'obj_key': '経験豊富', 'obj': '経験豊富な男性', 'eng': 'well_experienced', 'o_adj': '', 'obj_p': 'な',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    147: {'all_key': '技術者', 'obj_key': '技術者', 'obj': '技術系男子', 'eng': 'engineer3', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    148: {'all_key': '友達の彼氏', 'obj_key': '友達の彼氏', 'obj': '友達の彼氏', 'eng': "friend's_boyfriend", 'o_adj': '',
          'obj_p': 'の', 'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '1',
          'type': 'only_obj'},
    149: {'all_key': 'ママ友の旦那さん', 'obj_key': 'ママ友の旦那さん', 'obj': 'ママ友の旦那さん', 'eng': "mommy_friend's_husband", 'o_adj': '',
          'obj_p': 'の', 'o_cat': 'c', 'o_ms': 'm', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '0',
          'type': 'only_obj'},
    150: {'all_key': 'テクニシャン', 'obj_key': 'テクニシャン', 'obj': 'テクニシャン', 'eng': 'technician', 'o_adj': '', 'obj_p': 'な',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '1', 'type': 'only_obj'},
    151: {'all_key': 'ドS', 'obj_key': 'ドS', 'obj': 'ドS男子', 'eng': 'de_s', 'o_adj': '', 'obj_p': 'な', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '1', 'type': 'only_obj'},
    152: {'all_key': 'マゾ', 'obj_key': 'マゾ', 'obj': 'M男クン', 'eng': 'masochist', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '1', 'type': 'only_obj'},
    153: {'all_key': 'BL好き', 'obj_key': 'BL好き', 'obj': 'BL男子', 'eng': 'boys_love', 'o_adj': '', 'obj_p': 'な',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '1', 'type': 'only_obj'},
    154: {'all_key': '妻子持ち', 'obj_key': '妻子持ち男性', 'obj': '妻子持ち男性', 'eng': 'tsumarako_man', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 'm', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '0', 'type': 'only_obj'},
    155: {'all_key': '宅配便', 'obj_key': '宅配便', 'obj': '宅配彼氏', 'eng': 'home_delivery', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    156: {'all_key': 'コンサルタント', 'obj_key': 'コンサルタント', 'obj': 'コンサル男子', 'eng': 'consultant', 'o_adj': '', 'obj_p': 'の',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    157: {'all_key': '将来性がある', 'obj_key': '将来性がある', 'obj': '将来有望男子', 'eng': 'in_the_future', 'o_adj': '', 'obj_p': 'no',
          'o_cat': 'c', 'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'},
    158: {'all_key': '年下', 'obj_key': '年下', 'obj': '年下男子', 'eng': 'younger', 'o_adj': '', 'obj_p': 'の', 'o_cat': 'c',
          'o_ms': 's', 'o_age': 'n', 'look': 'FALSE', 'o_sex': 'm', 'ad': '3', 'type': 'only_obj'}
}
