obj_key_list = [
    {'keyword': '３０代', 'adj': '性欲が強い', 'noun': '３０代女性', 'reason': 'この年代は性欲が強いから', 't_cat': 'a', 'ms': 's', 't_age': 'n',
     'look': False, 'eng': '30s', 'id': '0', 'pro': '３０代 セフレ', 'particle': 'の'},
    {'keyword': '４０代', 'adj': 'エッチな', 'noun': '４０代女性', 'reason': '性欲が強い年代だから', 't_cat': 'a', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': '40s', 'id': '1', 'pro': '４０代 セフレ', 'particle': 'の'},
    {'keyword': '５０代', 'adj': 'セックスが好きな', 'noun': '５０代女性', 'reason': 'セックスしたい人妻が多いから', 't_cat': 'a', 'ms': 's',
     't_age': 'o', 'look': False, 'eng': '50s', 'id': '2', 'pro': '５０代 セフレ', 'particle': 'の'},
    {'keyword': '６０代', 'adj': 'まだ現役の', 'noun': '６０代女性', 'reason': '不倫交際がしたい人妻が多いから', 't_cat': 'a', 'ms': 's',
     't_age': 'o',
     'look': False, 'eng': '60s', 'id': '3', 'pro': '６０代 セフレ', 'particle': 'の'},
    {'keyword': 'アブノーマル', 'adj': '特殊性癖の', 'noun': 'アブノーマル女性', 'reason': 'セックス好きでエッチなプレイを体験したいから', 't_cat': 'p',
     'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'abnormal', 'id': '4', 'pro': 'アブノーマル セフレ', 'particle': 'の'},
    {'keyword': '不倫妻', 'adj': '浮気したい', 'noun': '不倫妻', 'reason': '浮気セックスの願望が強いから', 't_cat': 's', 'ms': 'm', 't_age': 'n',
     'look': False, 'eng': 'adultery-wife', 'id': '5', 'pro': '不倫妻 セフレ', 'particle': 'の'},
    {'keyword': '素人', 'adj': 'エッチな', 'noun': '素人女性', 'reason': '意外にセックスが好きな人が多いから', 't_cat': 's', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'amateur', 'id': '6', 'pro': '素人 セフレ', 'particle': 'の'},
    {'keyword': 'アナルセックスOK', 'adj': 'エロい', 'noun': 'アナルセックスOKの女性', 'reason': 'エロい変態が多いから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'anal-sex', 'id': '7', 'pro': 'アナルセックス セフレ', 'particle': 'の'},
    {'keyword': 'おばさん', 'adj': 'エロい身体の', 'noun': 'おばさん', 'reason': '熟女好きな男性と出会いたいから', 't_cat': 'a', 'ms': 's',
     't_age': 'o',
     'look': False, 'eng': 'aunt', 'id': '8', 'pro': 'おばさん セフレ', 'particle': 'の'},
    {'keyword': '美少女', 'adj': 'かわいい', 'noun': '美少女', 'reason': '実はセックス願望が強いから', 't_cat': 'l', 'ms': 's', 't_age': 'y',
     'look': True, 'eng': 'beautiful-girl', 'id': '9', 'pro': '美少女 セフレ', 'particle': 'の'},
    {'keyword': '美魔女', 'adj': '性欲が強い', 'noun': '美魔女', 'reason': '性欲が強い人が多いから', 't_cat': 'l', 'ms': 's', 't_age': 'o',
     'look': True, 'eng': 'beautiful-mature', 'id': '10', 'pro': '美魔女 セフレ', 'particle': 'の'},
    {'keyword': '美人妻', 'adj': '欲求不満の', 'noun': '美人妻', 'reason': '欲求不満でセックスがしたいから', 't_cat': 'l', 'ms': 'm',
     't_age': 'n',
     'look': True, 'eng': 'beautiful-wife', 'id': '11', 'pro': '美人妻 セフレ', 'particle': 'の'},
    {'keyword': '美女', 'adj': 'モテモテの', 'noun': '美女', 'reason': 'エロいタイプの女の子が多いから', 't_cat': 'l', 'ms': 's', 't_age': 'n',
     'look': True, 'eng': 'beautiful-woman', 'id': '12', 'pro': '美女 セフレ', 'particle': 'の'},
    {'keyword': '美ボディ', 'adj': '巨乳な', 'noun': '美ボディ女子', 'reason': '実はドスケベでセックスが大好きだから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'beautiful-body', 'id': '13', 'pro': '美ボディ セフレ', 'particle': 'の'},
    {'keyword': 'ベツカレ女子', 'adj': '彼氏じゃ足りない', 'noun': 'ベツカレ女子', 'reason': 'スワップ願望があるから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'betsu-kare', 'id': '14', 'pro': 'ベツカレ セフレ', 'particle': 'の'},
    {'keyword': '巨乳', 'adj': 'エロおっぱいの', 'noun': '巨乳女性', 'reason': 'エロくていろんな体験をしたいから', 't_cat': 'b', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'big-boobs', 'id': '15', 'pro': '巨乳 セフレ', 'particle': 'の'},
    {'keyword': '爆乳', 'adj': 'フェラ好きな', 'noun': '爆乳女性', 'reason': 'エロい体験をしたいから', 't_cat': 'b', 'ms': 's', 't_age': 'n',
     'look': False, 'eng': 'big-tits', 'id': '16', 'pro': '爆乳 セフレ', 'particle': 'の'},
    {'keyword': 'バイセクシャル', 'adj': '恋人がいる', 'noun': 'バイセクシャルの女性', 'reason': 'レズビアンの恋人だけでは物足りないから', 't_cat': 'p',
     'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'bisexual', 'id': '17', 'pro': 'バイセクシャル セフレ', 'particle': 'の'},
    {'keyword': '金髪美女', 'adj': '刺激的な', 'noun': '金髪美女', 'reason': '外国人との体験をしたいと思っているから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'blond-hair', 'id': '18', 'pro': '金髪美女 セフレ', 'particle': 'の'},
    {'keyword': 'ブサカワ', 'adj': 'ブスでもエロい', 'noun': 'ブサカワ女子', 'reason': 'ブスだけど巨乳でセックスが好きだから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'busakawa', 'id': '19', 'pro': 'ブサカワ セフレ', 'particle': 'の'},
    {'keyword': 'キャバ嬢', 'adj': 'エッチな', 'noun': 'キャバ嬢', 'reason': 'エッチな男性が好きだから', 't_cat': 'j', 'ms': 's', 't_age': 'n',
     'look': False, 'eng': 'cabaret-hostess', 'id': '20', 'pro': 'キャバ嬢 セフレ', 'particle': 'の'},
    {'keyword': 'CA', 'adj': '美人な', 'noun': 'CAさん', 'reason': 'スタイルが良くてエロい身体の人が多いから', 't_cat': 'j', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'cabin-attendant', 'id': '21', 'pro': 'CA セフレ', 'particle': 'の'},
    {'keyword': '介護士', 'adj': 'ヤリマンの', 'noun': '介護士', 'reason': '職業柄ストレスが溜まりやすいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'carer', 'id': '22', 'pro': '介護士 セフレ', 'particle': 'の'},
    {'keyword': 'セレブ人妻', 'adj': '大人の魅力の', 'noun': 'セレブ女性', 'reason': '人妻だけどエッチな交際がしたいから', 't_cat': 's', 'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'celebrity', 'id': '23', 'pro': 'セレブ セフレ', 'particle': 'の'},
    {'keyword': '保育士', 'adj': '優しいけどエッチな', 'noun': '保育士', 'reason': '欲求不満でセックスがしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'childcare-worker', 'id': '24', 'pro': '保育士 セフレ', 'particle': 'の'},
    {'keyword': 'ちょいブサ女子', 'adj': '巨乳でエロい', 'noun': 'ちょいブサ女子', 'reason': 'ブスでもセックスがしたいから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'choi-busa', 'id': '25', 'pro': 'ちょいブサ セフレ', 'particle': 'の'},
    {'keyword': 'デブ専', 'adj': '変態な', 'noun': 'デブ専女性', 'reason': 'セックスが好きでアダルトな体験がしたいから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'chubbychaser', 'id': '26', 'pro': 'デブ専 セフレ', 'particle': 'の'},
    {'keyword': 'ヤリマン', 'adj': '素人だけど', 'noun': 'ヤリマンな女性', 'reason': 'エロい体験がしたいので', 't_cat': 'p', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'loose', 'id': '27', 'pro': 'ヤリマン セフレ', 'particle': 'の'},
    {'keyword': 'ショップ店員', 'adj': '評判のいい', 'noun': 'ショップ店員', 'reason': '純粋にセックスを楽しめる相手を探しているから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'clerk', 'id': '28', 'pro': 'ショップ店員 セフレ', 'particle': 'の'},
    {'keyword': '女子大生', 'adj': '真面目そうな', 'noun': '女子大生', 'reason': '実はエッチな経験がしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'y',
     'look': False, 'eng': 'college-woman', 'id': '29', 'pro': '女子大生 セフレ', 'particle': 'の'},
    {'keyword': '風俗嬢', 'adj': '本番がしたい', 'noun': '風俗嬢', 'reason': 'デリヘルやヘルス勤務ではセックスできないから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'customs-miss', 'id': '30', 'pro': '風俗嬢 セフレ', 'particle': 'の'},
    {'keyword': 'バツイチ', 'adj': '男性に飢えた', 'noun': 'バツイチ女性', 'reason': '男性といろいろな体験をしたいから', 't_cat': 's', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'divorced', 'id': '31', 'pro': 'バツイチ セフレ', 'particle': 'の'},
    {'keyword': '家事手伝い', 'adj': '男好きな', 'noun': '家事手伝いの女性', 'reason': 'ストレスが溜まっているから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'domestic-help', 'id': '32', 'pro': '家事手伝い セフレ', 'particle': 'の'},
    {'keyword': 'エリート女性', 'adj': '高学歴の', 'noun': 'エリート女性', 'reason': '性欲が強くてストレスが溜まるから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'elite', 'id': '33', 'pro': 'エリート セフレ', 'particle': 'の'},
    {'keyword': 'エロ女', 'adj': '欲求不満な', 'noun': 'エロ女', 'reason': 'エッチでセックスがしたいから', 't_cat': 'p', 'ms': 's', 't_age': 'n',
     'look': False, 'eng': 'erotic', 'id': '34', 'pro': 'エロ女 セフレ', 'particle': 'の'},
    {'keyword': '変態', 'adj': '超絶エロな', 'noun': '変態女性', 'reason': '興奮できるエロいプレイがしたいから', 't_cat': 'p', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'erotopathy', 'id': '35', 'pro': '変態 セフレ', 'particle': 'の'},
    {'keyword': 'Fカップ', 'adj': 'ムチムチの', 'noun': 'Fカップ女性', 'reason': '秘密でエッチな体験がしたいから', 't_cat': 'b', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'f-cup', 'id': '36', 'pro': 'Fカップ セフレ', 'particle': 'の'},
    {'keyword': '五十路', 'adj': '町内の', 'noun': '五十路の女性', 'reason': '人妻だから近所では出会えないから', 't_cat': 'a', 'ms': 's',
     't_age': 'o',
     'look': False, 'eng': 'fifties', 'id': '37', 'pro': '五十路 セフレ', 'particle': 'の'},
    {'keyword': 'スチュワーデス', 'adj': 'いい身体の', 'noun': 'スチュワーデス', 'reason': '仕事の緊張をほぐしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'flight-attendant', 'id': '38', 'pro': 'スチュワーデス セフレ', 'particle': 'の'},
    {'keyword': '外国人', 'adj': '彼氏がいる', 'noun': '外国人', 'reason': '日本人と浮気の恋愛がしたいから', 't_cat': 's', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'foreigner', 'id': '39', 'pro': '外国人 セフレ', 'particle': 'の'},
    {'keyword': '四十路', 'adj': '淫乱な', 'noun': '四十路の女性', 'reason': '人妻だけど素人とセックスしたいから', 't_cat': 'a', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'forties', 'id': '40', 'pro': '四十路 セフレ', 'particle': 'の'},
    {'keyword': '専業主婦', 'adj': '不倫がしたい', 'noun': '専業主婦', 'reason': '不倫相手の男性を探しているから', 't_cat': 's', 'ms': 'm',
     't_age': 'n',
     'look': False, 'eng': 'full-time-homemaker', 'id': '41', 'pro': '専業主婦 セフレ', 'particle': 'の'},
    {'keyword': 'ギャル', 'adj': 'エッチな', 'noun': 'ギャル', 'reason': 'ヤリマンでいろんなタイプの男とヤリたいから', 't_cat': 'c', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'gal', 'id': '42', 'pro': 'ギャル セフレ', 'particle': 'の'},
    {'keyword': 'オタク', 'adj': 'コスプレ好きの', 'noun': 'オタク女子', 'reason': '本当はエロくて、趣味もセックスも好きだから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'geek', 'id': '43', 'pro': 'オタク セフレ', 'particle': 'の'},
    {'keyword': 'メガネ女子', 'adj': 'エロ体験がしたい', 'noun': 'メガネ女子', 'reason': '本当は性欲が強いのを隠しているから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'glasses', 'id': '44', 'pro': 'メガネ女子 セフレ', 'particle': 'の'},
    {'keyword': '公務員', 'adj': 'モテる', 'noun': '公務員女子', 'reason': '優良なセックスの相手を探す女子が多いので', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'government-employee', 'id': '45', 'pro': '公務員 セフレ', 'particle': 'の'},
    {'keyword': '大学院生', 'adj': 'セックスレスの', 'noun': '女子大学院生', 'reason': '特に理系はエッチな女子が多いので', 't_cat': 'j', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'graduate-student', 'id': '46', 'pro': '大学院生 セフレ', 'particle': 'の'},
    {'keyword': '美容師', 'adj': 'ヤリマンの', 'noun': '美容師', 'reason': '職業柄、人に触るのでセックスも好きだから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'hairdresser', 'id': '47', 'pro': '美容師 セフレ', 'particle': 'の'},
    {'keyword': '同性愛', 'adj': 'レズの', 'noun': '同性愛者の女性', 'reason': 'レズセックスだけでは物足りないから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'homosexuality', 'id': '48', 'pro': '同性愛 セフレ', 'particle': 'の'},
    {'keyword': 'ホステス', 'adj': 'エロい', 'noun': 'ホステスさん', 'reason': '男性関係の悩みの欲求不満を解消したいので', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'hostess', 'id': '49', 'pro': 'ホステス セフレ', 'particle': 'の'},
    {'keyword': 'アイドル', 'adj': 'ナイスボディの', 'noun': 'アイドル', 'reason': '過激なセックスを体験したいので', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'idol', 'id': '50', 'pro': 'アイドル セフレ', 'particle': 'の'},
    {'keyword': 'インテリ', 'adj': '淫乱な', 'noun': 'インテリ女性', 'reason': '実は淫乱でエロいセックスを体験したいので', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'intelligentzia', 'id': '51', 'pro': 'インテリ セフレ', 'particle': 'の'},
    {'keyword': '短大生', 'adj': 'ワケありの', 'noun': '女子短大生', 'reason': '早くセックスを体験してみたいと思っているので', 't_cat': 'j', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'junior-college-student', 'id': '52', 'pro': '短大生 セフレ', 'particle': 'の'},
    {'keyword': 'レズ', 'adj': 'テクニックのある', 'noun': 'レズ女性', 'reason': 'レズビアンとのセックスだけでは物足りないから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'lesbian', 'id': '53', 'pro': 'レズ セフレ', 'particle': 'の'},
    {'keyword': '文系女子', 'adj': '経験豊富な', 'noun': '文系女子', 'reason': '恋愛もセックスも同じように楽しみたいから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'liberal-arts-woman', 'id': '54', 'pro': '文系女子 セフレ', 'particle': 'の'},
    {'keyword': '一人暮らし', 'adj': 'ホテル不要の', 'noun': '一人暮らし女子', 'reason': '一人暮らしは寂しいときがあるので', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'live-alone', 'id': '55', 'pro': '一人暮らし セフレ', 'particle': 'の'},
    {'keyword': 'ロリ系', 'adj': 'かわいい', 'noun': 'ロリ系女子', 'reason': '実はエッチで、こっそりセックスしたいから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'lolita', 'id': '56', 'pro': 'ロリ系 セフレ', 'particle': 'の'},
    {'keyword': 'ママ活女子', 'adj': '肉体関係ありの', 'noun': 'ママ活女子', 'reason': 'お金にはもう満足していて、あとはセックスが不満なので', 't_cat': 'p',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'mama-katsu', 'id': '57', 'pro': 'ママ活 セフレ', 'particle': 'の'},
    {'keyword': 'ドM', 'adj': '調教されたい', 'noun': 'ドM女性', 'reason': '時間をかけて調教してくれる男性が欲しいから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'masochist', 'id': '58', 'pro': 'ドM セフレ', 'particle': 'の'},
    {'keyword': '熟女', 'adj': '性欲旺盛な', 'noun': '熟女', 'reason': '年齢的に人生で一番エロい時期なので', 't_cat': 'a', 'ms': 's',
     't_age': 'o',
     'look': False, 'eng': 'mature', 'id': '59', 'pro': '熟女 セフレ', 'particle': 'の'},
    {'keyword': 'メンヘラ', 'adj': 'ビッチな', 'noun': 'メンヘラな女性', 'reason': '病気のせいで貞操観念が弱くなっているので', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'mental-health', 'id': '60', 'pro': 'メンヘラ セフレ', 'particle': 'の'},
    {'keyword': '中年', 'adj': 'エロい', 'noun': '中年女性', 'reason': '性欲が強くなる年代なので', 't_cat': 'a', 'ms': 's', 't_age': 'o',
     'look': False, 'eng': 'middle-age', 'id': '61', 'pro': '中年 セフレ', 'particle': 'の'},
    {'keyword': '中高年', 'adj': '熟年の', 'noun': '中高年女性', 'reason': 'シニアになって、あまりセックスできないので', 't_cat': 'a', 'ms': 's',
     't_age': 'o', 'look': False, 'eng': 'middle-and-old-age', 'id': '62', 'pro': '中高年 セフレ', 'particle': 'の'},
    {'keyword': '未成年', 'adj': '１８歳以上の', 'noun': '未成年女子', 'reason': 'セックスを覚えたばかりでやりたい盛りなので', 't_cat': 'a', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'minor', 'id': '63', 'pro': '未成年 セフレ', 'particle': 'の'},
    {'keyword': 'モデル', 'adj': 'スタイル抜群の', 'noun': 'モデル', 'reason': '体型を維持するストレスが溜まっているので', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'model', 'id': '64', 'pro': 'モデル セフレ', 'particle': 'の'},
    {'keyword': '清楚な', 'adj': '実はエッチな', 'noun': '清楚女子', 'reason': '清楚に見えるけど実はエッチでセックスが好きだから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'neat-and-clean', 'id': '65', 'pro': '清楚 セフレ', 'particle': 'の'},
    {'keyword': '新婚の若妻', 'adj': '旦那に不満な', 'noun': '新婚若妻', 'reason': '旦那との夜の生活に不満があるので', 't_cat': 's', 'ms': 'm',
     't_age': 'y', 'look': False, 'eng': 'newly-wed', 'id': '66', 'pro': '新婚 若妻 セフレ', 'particle': 'の'},
    {'keyword': 'ナース', 'adj': 'エッチな', 'noun': 'ナース', 'reason': '病院での仕事のストレスが溜まっているので', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'nurse', 'id': '67', 'pro': 'ナース セフレ', 'particle': 'の'},
    {'keyword': 'OL', 'adj': 'スケべな', 'noun': 'OL', 'reason': 'テクニックのある男性とセックスしたいので', 't_cat': 'j', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'office-lady', 'id': '68', 'pro': 'OL セフレ', 'particle': 'の'},
    {'keyword': 'パパ活女子', 'adj': 'セックスできる', 'noun': 'パパ活女子', 'reason': 'パパ活でセックスするのに慣れているので', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'papa-katsu', 'id': '69', 'pro': 'パパ活 セフレ', 'particle': 'の'},
    {'keyword': '子持ち', 'adj': '欲求不満な', 'noun': '子持ち女性', 'reason': '性欲が強いのに子育てでセックスできないから', 't_cat': 's', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'parenthood', 'id': '70', 'pro': '子持ち セフレ', 'particle': 'の'},
    {'keyword': 'フリーター', 'adj': '独身の', 'noun': 'フリーター女子', 'reason': '日々の暮らしで疲れていて癒されたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'part-time-worker', 'id': '71', 'pro': 'フリーター セフレ', 'particle': 'の'},
    {'keyword': 'パート主婦', 'adj': '不倫したい', 'noun': 'パート主婦', 'reason': '人妻だけどこっそり浮気ができるから', 't_cat': 's', 'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'part-timer-wife', 'id': '72', 'pro': 'パート主婦 セフレ', 'particle': 'の'},
    {'keyword': '中出しOK', 'adj': 'エロい', 'noun': '中出しOKの女性', 'reason': '安全で長く付き合えるセックスの相手が欲しいから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'pies', 'id': '73', 'pro': '中出し セフレ', 'particle': 'の'},
    {'keyword': 'ぽっちゃり', 'adj': 'ブスじゃない', 'noun': 'ぽっちゃり女子', 'reason': 'ぽっちゃりでもセックスしてくれる男性と出会いたいから', 't_cat': 'b',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'plump', 'id': '74', 'pro': 'ぽっちゃり セフレ', 'particle': 'の'},
    {'keyword': 'AV女優', 'adj': 'セックス好きな', 'noun': 'AV女優', 'reason': 'プライベートでは自分が好きなようにセックスがしたいから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'porn-actress', 'id': '75', 'pro': 'AV女優 セフレ', 'particle': 'の'},
    {'keyword': '読者モデル', 'adj': 'モテる', 'noun': '読モ', 'reason': '男性にモテるけど、セックスはリラックスしてしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'y', 'look': True, 'eng': 'reader-model', 'id': '76', 'pro': '読者モデル セフレ', 'particle': 'の'},
    {'keyword': '受付嬢', 'adj': 'モデル級の', 'noun': '受付嬢', 'reason': '職場の人に知られずセックスを楽しみたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'receptionist', 'id': '77', 'pro': '受付嬢 セフレ', 'particle': 'の'},
    {'keyword': 'お金持ち', 'adj': '結婚している', 'noun': 'お金持ち女性', 'reason': '知らない男性とのセックスを楽しみたいから', 't_cat': 's', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'rich', 'id': '78', 'pro': 'お金持ち セフレ', 'particle': 'の'},
    {'keyword': '家出少女', 'adj': '地方の', 'noun': '家出少女', 'reason': '地方から出てきて優しい男性と知り合いたいから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'runaway-girl', 'id': '79', 'pro': '家出少女 セフレ', 'particle': 'の'},
    {'keyword': 'ドS', 'adj': '奴隷が欲しい', 'noun': 'ドSの女性', 'reason': '従順なドMの奴隷が欲しいから', 't_cat': 'p', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'sadist', 'id': '80', 'pro': 'ドS セフレ', 'particle': 'の'},
    {'keyword': 'セックス中毒', 'adj': '満足できない', 'noun': 'セックス中毒の女性', 'reason': 'とにかくセックスが好きな男性とヤリたいから', 't_cat': 'p',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'sex-dependency', 'id': '81', 'pro': 'セックス中毒 セフレ', 'particle': 'の'},
    {'keyword': 'セックス依存症', 'adj': 'ヤリマンの', 'noun': 'セックス依存症の女性', 'reason': '継続してセックスできる相手が欲しいから', 't_cat': 'p',
     'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'sexual-addiction', 'id': '82', 'pro': 'セックス依存症 セフレ', 'particle': 'の'},
    {'keyword': 'パイパン', 'adj': 'エロい', 'noun': 'パイパン女子', 'reason': 'パイパンでたくさんセックスを楽しみたいから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'shaved', 'id': '83', 'pro': 'パイパン セフレ', 'particle': 'の'},
    {'keyword': 'ニューハーフ', 'adj': '女装した', 'noun': 'ニューハーフ', 'reason': 'ノンケ男性とセックスを楽しみたいから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'shirtlifter', 'id': '84', 'pro': 'ニューハーフ セフレ', 'particle': 'の'},
    {'keyword': 'ショートカット', 'adj': 'カワいい', 'noun': 'ショートカット女子', 'reason': 'アクティブにセックスを楽しめる人と会いたいから', 't_cat': 'l',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'short-haircut', 'id': '85', 'pro': 'ショートカット セフレ', 'particle': 'の'},
    {'keyword': 'シンママ', 'adj': '出会い募集の', 'noun': 'シンママ', 'reason': 'セックスができる男性との出会いを探しているから', 't_cat': 's', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'sin-mama', 'id': '86', 'pro': 'シンママ セフレ', 'particle': 'の'},
    {'keyword': '独身', 'adj': '相手が欲しい', 'noun': '独身女性', 'reason': '純粋にセックスを楽しめる男性と出会いたいから', 't_cat': 's', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'single', 'id': '87', 'pro': '独身 セフレ', 'particle': 'の'},
    {'keyword': 'シングルマザー', 'adj': '欲求不満の', 'noun': 'シングルマザー', 'reason': '子供のストレスをセックスで解消したいから', 't_cat': 's', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'single-mother', 'id': '88', 'pro': 'シングルマザー セフレ', 'particle': 'の'},
    {'keyword': '奴隷', 'adj': '従順な', 'noun': '奴隷女性', 'reason': '調教してくれるご主人様が欲しいから', 't_cat': 'p', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'slave', 'id': '89', 'pro': '奴隷 セフレ', 'particle': 'の'},
    {'keyword': '痴女', 'adj': '射精させたい', 'noun': '痴女', 'reason': '痴女れるM男と知り合いたいから', 't_cat': 'p', 'ms': 's', 't_age': 'n',
     'look': False, 'eng': 'slut', 'id': '90', 'pro': '痴女 セフレ', 'particle': 'の'},
    {'keyword': 'SM好き', 'adj': '変態な', 'noun': 'SM好きの女性', 'reason': '自分とプレイの相性がいい相手を探しているから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'sm', 'id': '91', 'pro': 'SM好き セフレ', 'particle': 'の'},
    {'keyword': 'スポーツインストラクター', 'adj': '美ボディの', 'noun': 'スポーツインストラクター', 'reason': '体力の続く限りセックスできる相手を探しているから',
     't_cat': 'j', 'ms': 's', 't_age': 'n', 'look': False, 'eng': 'sports-instructor', 'id': '92',
     'pro': 'スポーツインストラクター セフレ', 'particle': 'の'},
    {'keyword': '子連れママ', 'adj': 'ギャルの', 'noun': '子連れママ', 'reason': '子供を育てる欲求不満をセックスで発散したいから', 't_cat': 's', 'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'taking-children', 'id': '93', 'pro': '子連れ セフレ', 'particle': 'の'},
    {'keyword': '女教師', 'adj': 'エロい', 'noun': '女教師', 'reason': '堅い仕事で、プライベートではハメを外したいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'teacher', 'id': '94', 'pro': '女教師 セフレ', 'particle': 'の'},
    {'keyword': '１０代', 'adj': 'エッチな', 'noun': '１０代女子', 'reason': '１８歳を過ぎてセックスを楽しめるようになったから', 't_cat': 'a', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'teenagers', 'id': '95', 'pro': '１０代 セフレ', 'particle': 'の'},
    {'keyword': '三十路', 'adj': '素人の', 'noun': '三十路女性', 'reason': '３０歳を過ぎて性欲がピークに達しているので', 't_cat': 'a', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'thirties', 'id': '96', 'pro': '三十路 セフレ', 'particle': 'の'},
    {'keyword': '貧乳', 'adj': '興奮する', 'noun': '貧乳女子', 'reason': '刺激的なセックスができる男性と長く付き合いたいから', 't_cat': 'b', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'tits', 'id': '97', 'pro': '貧乳 セフレ', 'particle': 'の'},
    {'keyword': 'ツンデレ', 'adj': '実はエロい', 'noun': 'ツンデレ女子', 'reason': '出会い系だとツンデレ好きな男性と知り合いやすいから', 't_cat': 'c',
     'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'tsundere', 'id': '98', 'pro': 'ツンデレ セフレ', 'particle': 'の'},
    {'keyword': '家庭教師', 'adj': 'キスが好きな', 'noun': '家庭教師', 'reason': '子供に勉強を教えてストレスが溜まっているため', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'tutor', 'id': '99', 'pro': '家庭教師 セフレ', 'particle': 'の'},
    {'keyword': '２０代', 'adj': 'おじさん好きな', 'noun': '２０代女子', 'reason': '大人の男性の優しくて執拗なセックスが好きだから', 't_cat': 'a', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'twenties', 'id': '100', 'pro': '２０代 セフレ', 'particle': 'の'},
    {'keyword': 'ブサイク', 'adj': 'ヤレる', 'noun': 'ブサイク女子', 'reason': 'ブサイクでもセックスしてくれる男性を探しているから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'ugly', 'id': '101', 'pro': 'ブサイク セフレ', 'particle': 'の'},
    {'keyword': '浮気妻', 'adj': '不倫願望のある', 'noun': '浮気妻', 'reason': '出会い系ならバレずにセックスできる相手と出会えるから', 't_cat': 's', 'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'unfaithful-wife', 'id': '102', 'pro': '浮気妻 セフレ', 'particle': 'の'},
    {'keyword': '近所の奥さん', 'adj': 'エロい', 'noun': '近所の奥さん', 'reason': '出会い系サイトならバレずに近所の男性と知り合えるから', 't_cat': 's',
     'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'vicinity-wife', 'id': '103', 'pro': '近所 奥さん セフレ', 'particle': 'の'},
    {'keyword': '処女', 'adj': '清楚な', 'noun': '処女', 'reason': '優しい初めての相手を探しているから', 't_cat': 'c', 'ms': 's', 't_age': 'n',
     'look': False, 'eng': 'virgin', 'id': '104', 'pro': '処女 セフレ', 'particle': 'の'},
    {'keyword': '専門学生', 'adj': 'SEX好きな', 'noun': '専門学生', 'reason': '大人の優しい男性が好きなので', 't_cat': 'j', 'ms': 's',
     't_age': 'y',
     'look': False, 'eng': 'vocational-school-student', 'id': '105', 'pro': '専門学生 セフレ', 'particle': 'の'},
    {'keyword': '人妻', 'adj': 'エッチな', 'noun': '人妻', 'reason': 'セックスが好きだから', 't_cat': 's', 'ms': 'm', 't_age': 'n',
     'look': False, 'eng': 'adultery-married-woman', 'id': '106', 'pro': '専門学生 セフレ', 'particle': 'の'},
    {'keyword': '就活生', 'adj': 'リクスーの', 'noun': '就活生', 'reason': '就職活動のストレスで夜遊びしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'job-hunting-students', 'id': '107', 'pro': '就活生 セフレ', 'particle': 'の'},
    {'keyword': 'スレンダー', 'adj': 'エロい', 'noun': 'スレンダー<!--woman-->', 'reason': '車内などでエッチな体験をしたいから', 't_cat': 'b',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'slender', 'id': '108', 'pro': 'スレンダー セフレ', 'particle': 'の'},
    {'keyword': '細身', 'adj': '巨乳だけど', 'noun': '細身<!--woman-->', 'reason': 'エロい体型でセックス慣れしているから', 't_cat': 'b', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'thin-figure', 'id': '109', 'pro': '細身 セフレ', 'particle': 'の'},
    {'keyword': '女医', 'adj': 'エロ美人の', 'noun': '女医', 'reason': '仕事のストレスでセックスしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'woman-doctor', 'id': '110', 'pro': '女医 セフレ', 'particle': 'の'},
    {'keyword': '妊婦', 'adj': 'セックス好きな', 'noun': '妊婦', 'reason': '妊娠していて旦那とセックスできないから', 't_cat': 's', 'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'pregnant', 'id': '111', 'pro': '妊婦 セフレ', 'particle': 'の'},
    {'keyword': 'セックスレス', 'adj': '不倫希望の', 'noun': 'セックスレス人妻', 'reason': '性欲解消できる浮気相手の男性を探しているから', 't_cat': 's',
     'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'sexless', 'id': '112', 'pro': 'セックスレス セフレ', 'particle': 'の'},
    {'keyword': 'セカンドヴァージン', 'adj': '魅力的な', 'noun': 'セカンドヴァージンの<!--woman-->', 'reason': 'ずっとセックスがご無沙汰だから', 't_cat': 'p',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'second-virgin', 'id': '113', 'pro': 'セカンドヴァージン セフレ',
     'particle': 'の'},
    {'keyword': '地下アイドル', 'adj': '美人な', 'noun': '地下アイドル', 'reason': '恋愛禁止だけどセックスしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'underground-idol', 'id': '114', 'pro': '地下アイドル セフレ', 'particle': 'の'},
    {'keyword': '激ぽちゃ', 'adj': '中年好きの', 'noun': '激ぽちゃ<!--woman-->', 'reason': 'なかなかセックス相手が見つからないから', 't_cat': 'b',
     'ms': 's', 't_age': 'n', 'look': True, 'eng': 'very-plump', 'id': '115', 'pro': '激ぽちゃ セフレ', 'particle': 'の'},
    {'keyword': 'ショートヘア', 'adj': '素人の', 'noun': 'ショートヘア<!--woman-->', 'reason': '性欲も活発で相手を探しているから', 't_cat': 'l',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'short-hair', 'id': '116', 'pro': 'ショートヘア セフレ', 'particle': 'の'},
    {'keyword': '未亡人', 'adj': 'エッチな', 'noun': '未亡人', 'reason': 'エッチだけど旦那がいなくてセックスできないから', 't_cat': 's', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'widow', 'id': '117', 'pro': '未亡人 セフレ', 'particle': 'の'},
    {'keyword': 'メイド', 'adj': 'エロい', 'noun': 'メイド', 'reason': 'メイド喫茶でエッチな気分になっているから', 't_cat': 'j', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'maid', 'id': '118', 'pro': 'メイド セフレ', 'particle': 'の'},
    {'keyword': '腐女子', 'adj': '美少女の', 'noun': '腐女子', 'reason': 'オタクでなかなかセックスできないから', 't_cat': 'c', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'yaoi-fandom', 'id': '119', 'pro': '腐女子 セフレ', 'particle': 'の'},
    {'keyword': '新妻', 'adj': '不倫したい', 'noun': '新妻', 'reason': 'アプリならバレずに不倫できるから', 't_cat': 's', 'ms': 'm', 't_age': 'n',
     'look': False, 'eng': 'new-wife', 'id': '120', 'pro': '新妻 セフレ', 'particle': 'の'},
    {'keyword': 'お嬢様', 'adj': 'セックスしたい', 'noun': 'お嬢様', 'reason': '自由なセックスに興味があるから', 't_cat': 'c', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'lady', 'id': '121', 'pro': 'お嬢様 セフレ', 'particle': 'の'},
    {'keyword': '生保レディ', 'adj': 'SEX好きな', 'noun': '生保セールスレディ', 'reason': 'あわよくば契約が取れそうだから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'life-insurance-lady', 'id': '122', 'pro': '生保レディ セフレ', 'particle': 'の'},
    {'keyword': 'デザイナー', 'adj': '絶倫の', 'noun': 'デザイナー', 'reason': 'いろんな体験をしたいから', 't_cat': 'j', 'ms': 's', 't_age': 'n',
     'look': False, 'eng': 'designer', 'id': '123', 'pro': 'デザイナー セフレ', 'particle': 'の'},
    {'keyword': 'エンジニア', 'adj': 'アダルトな', 'noun': '女性エンジニア', 'reason': '仕事のストレスをセックスで解消したいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'engineer', 'id': '124', 'pro': 'エンジニア セフレ', 'particle': 'の'},
    {'keyword': '元カノ', 'adj': '復縁したい', 'noun': '元カノ', 'reason': '体の相性がいいから', 't_cat': 's', 'ms': 's', 't_age': 'n',
     'look': False, 'eng': 'ex-girlfriend', 'id': '125', 'pro': '元カノ セフレ', 'particle': 'の'},
    {'keyword': 'エステティシャン', 'adj': '美人な', 'noun': 'エステティシャン', 'reason': 'セックスが好きだから', 't_cat': 'j', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'esthetician', 'id': '126', 'pro': 'エステティシャン セフレ', 'particle': 'の'},
    {'keyword': 'アパレル店員', 'adj': 'ナンパされる', 'noun': 'アパレル店員', 'reason': 'ナンパじゃなくて安心できる人と出会いたいから', 't_cat': 'j',
     'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'apparel-clerk', 'id': '127', 'pro': 'アパレル セックス', 'particle': 'の'},
    {'keyword': '巨乳人妻', 'adj': '素人の', 'noun': '巨乳人妻', 'reason': 'エロくて夫のセックスでは物足りないから', 't_cat': 'b', 'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'big-boobs-wife', 'id': '128', 'pro': '巨乳 人妻 セックス', 'particle': 'の'},
    {'keyword': '芸能人', 'adj': 'エロい', 'noun': '女性芸能人', 'reason': 'エロくて、セックスで満たされていないから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'entertainer', 'id': '129', 'pro': '芸能人 セックス', 'particle': 'の'},
    {'keyword': 'グラマー', 'adj': 'エッチな', 'noun': 'グラマー<!--woman-n-->', 'reason': 'エッチな身体をもてあまし気味だから', 't_cat': 'b',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'glamorous-girl', 'id': '130', 'pro': 'グラマー セックス', 'particle': 'な'},
    {'keyword': 'バレーボール選手', 'adj': 'おっぱい大きい', 'noun': 'バレーボール選手', 'reason': 'アスリートは性欲が強いから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'volleyball-player', 'id': '131', 'pro': 'バレーボール セックス', 'particle': 'の'},
    {'keyword': 'ソープ嬢', 'adj': 'テクのある', 'noun': 'ソープ嬢', 'reason': '自分が気持ちよくなれるセックスがしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'soapland-girl', 'id': '132', 'pro': 'ソープ嬢 セックス', 'particle': 'の'},
    {'keyword': '現役学生', 'adj': 'SEXデビューしたい', 'noun': '現役女子学生', 'reason': '周りがデビューして焦っているから', 't_cat': 'j', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'active-student', 'id': '133', 'pro': '現役 学生 セックス', 'particle': 'の'},
    {'keyword': '同級生', 'adj': '美人な', 'noun': '同級生の<!--woman-->', 'reason': '同じ年齢の男性とするのが好きだから', 't_cat': 's', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'classmate', 'id': '134', 'pro': '同級生 セックス', 'particle': 'の'},
    {'keyword': 'キャリアウーマン', 'adj': '実はエッチな', 'noun': 'キャリアウーマン', 'reason': '仕事のストレスをセックスで解消したいから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'career-woman', 'id': '135', 'pro': 'キャリアウーマン セックス',
     'particle': 'の'},
    {'keyword': 'マッサージ師', 'adj': '潮吹きしやすい', 'noun': '女性マッサージ師', 'reason': '自分が気持ちよくして欲しいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'masseur', 'id': '136', 'pro': 'マッサージ セックス', 'particle': 'の'},
    {'keyword': '制服女子', 'adj': 'コスじゃない', 'noun': '制服女子', 'reason': '制服の着てのセックスが燃えるから', 't_cat': 'j', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'uniform-woman', 'id': '137', 'pro': '制服 セックス', 'particle': 'の'},
    {'keyword': '教育実習生', 'adj': 'エッチな', 'noun': '教育実習生', 'reason': '慣れない学校のストレスから解放されたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'y', 'look': False, 'eng': 'student-teacher', 'id': '138', 'pro': '教育実習生 セックス', 'particle': 'の'},
    {'keyword': 'リクルートスーツ女子', 'adj': 'SEX好きな', 'noun': 'リクルートスーツ女子', 'reason': '大学や女子大ではない出会いを探しているから', 't_cat': 'c',
     'ms': 's', 't_age': 'y', 'look': False, 'eng': 'recruit-suit', 'id': '139', 'pro': 'リクルートスーツ女子 セックス',
     'particle': 'の'},
    {'keyword': '美大生', 'adj': 'モデル似の', 'noun': '女子美大生', 'reason': '表現する人はセックスが好きだから', 't_cat': 'j', 'ms': 's',
     't_age': 'y',
     'look': False, 'eng': 'art-student', 'id': '140', 'pro': '美大生 セックス', 'particle': 'の'},
    {'keyword': '愛人', 'adj': 'おじさん好きな', 'noun': '愛人', 'reason': '愛人をしていて年上好きになっているから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'mistress', 'id': '141', 'pro': '愛人 セックス', 'particle': 'の'},
    {'keyword': '童顔', 'adj': 'ロリな', 'noun': '童顔女子', 'reason': '童顔であまりセックスができていないから', 't_cat': 'l', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'baby-face', 'id': '142', 'pro': '童顔 セックス', 'particle': 'の'},
    {'keyword': '小悪魔', 'adj': 'エロい', 'noun': '小悪魔系女子', 'reason': 'エッチが好きでできる相手をいつも探しているから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'teaser', 'id': '143', 'pro': '小悪魔 セックス', 'particle': 'の'},
    {'keyword': '営業レディ', 'adj': 'アダルトな', 'noun': '営業レディ', 'reason': '営業のストレスでセックスがしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'sales-lady', 'id': '144', 'pro': '営業 セックス', 'particle': 'の'},
    {'keyword': 'エロカワ', 'adj': '巨乳の', 'noun': 'エロカワ<!--woman-n-->', 'reason': '純粋にエッチが好きだから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'erotic-and-pretty', 'id': '145', 'pro': 'エロカワ セックス', 'particle': 'な'},
    {'keyword': '体育会系', 'adj': '引き締まった', 'noun': '体育会系女子', 'reason': '体力があって性欲も強いから', 't_cat': 'c', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'athretic', 'id': '146', 'pro': '体育会系 セックス', 'particle': 'の'},
    {'keyword': '高学歴', 'adj': 'エリートの', 'noun': '高学歴<!--woman-n-->', 'reason': '頭がいい女性は性欲が強いから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'well-educated-woman', 'id': '147', 'pro': '高学歴 セックス', 'particle': 'の'},
    {'keyword': '中卒', 'adj': 'ハメ撮りOKの', 'noun': '中卒<!--woman-n-->', 'reason': '承認欲求をセックスで満たしたいから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'junior-high-graduate', 'id': '148', 'pro': '中卒 セックス',
     'particle': 'の'},
    {'keyword': '貧困女子', 'adj': '売春しない', 'noun': '貧困女子', 'reason': 'セックスをしてでも優しい人に助けて欲しいから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'poverty', 'id': '149', 'pro': '貧困女子 セックス', 'particle': 'の'},
    {'keyword': '妹系', 'adj': '美少女の', 'noun': '妹系女子', 'reason': '優しいお兄ちゃんを探しているから', 't_cat': 'c', 'ms': 'm',
     't_age': 'y',
     'look': False, 'eng': 'lovely', 'id': '150', 'pro': '妹系 セックス', 'particle': 'の'},
    {'keyword': '美人奥様', 'adj': '不倫したい', 'noun': '美人奥様', 'reason': '不倫セックスのスリルを味わってみたいから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'beautiful-wife', 'id': '151', 'pro': '美人 奥様 セックス', 'particle': 'の'},
    {'keyword': '看護学生', 'adj': '彼氏持ちの', 'noun': '女子看護学生', 'reason': '彼氏がいてもセックスで満足していないから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'nursing-student', 'id': '152', 'pro': '看護学生 セックス', 'particle': 'の'},
    {'keyword': 'デパガ', 'adj': '制服が似合う', 'noun': 'デパートガール', 'reason': 'モテるけどなかなかセックスでは満足できないから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'elevator-operator', 'id': '153', 'pro': 'デパガ セックス', 'particle': 'の'},
    {'keyword': 'プロ彼女', 'adj': 'モテる', 'noun': 'プロ彼女', 'reason': '結婚する男性とは別にセックスの相手を探しているから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'professional-girl-friend', 'id': '154', 'pro': 'プロ彼女 セックス', 'particle': 'の'},
    {'keyword': 'アラサー', 'adj': 'エッチ好きな', 'noun': 'アラサー女子', 'reason': '仕事のストレスをセックスして解消したいから', 't_cat': 'a', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': '30-something', 'id': '155', 'pro': 'アラサー セックス', 'particle': 'の'},
    {'keyword': 'アラフォー', 'adj': 'セックスレスな', 'noun': 'アラフォー女性', 'reason': 'セックスレスで、誰でもいいからセックスしたいから', 't_cat': 'a',
     'ms': 's', 't_age': 'o', 'look': False, 'eng': '40-something', 'id': '156', 'pro': 'アラフォー セックス', 'particle': 'の'},
    {'keyword': 'ヤラハタ', 'adj': '処女の', 'noun': 'ヤラハタ女子', 'reason': '早くセックスして処女を捨てたいから', 't_cat': 'a', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'yarahata', 'id': '157', 'pro': 'ヤラハタ セックス', 'particle': 'の'},
    {'keyword': '美乳女子', 'adj': '素人の', 'noun': '美乳女子', 'reason': 'おっぱいの感度が良くてエッチだから', 't_cat': 'b', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'good-boobs', 'id': '158', 'pro': '美乳 セックス', 'particle': 'の'},
    {'keyword': 'ビッチ', 'adj': 'エロ過ぎる', 'noun': 'ビッチな<!--woman-->', 'reason': 'とにかく誰でもいいからセックスがしたいから', 't_cat': 'p',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'bitch', 'id': '159', 'pro': 'ビッチ セックス', 'particle': 'な'},
    {'keyword': '清純', 'adj': '実はエロい', 'noun': '清純女子', 'reason': '高嶺の花でなかなかセックスの相手が見つからないから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'pure', 'id': '160', 'pro': '清純 セックス', 'particle': 'な'},
    {'keyword': '優等生', 'adj': '実はエッチな', 'noun': '優等生女子', 'reason': 'エッチに興味はあるけど、なかなかセックスできないから', 't_cat': 'c',
     'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'honor-student', 'id': '161', 'pro': '優等生 セックス', 'particle': 'の'},
    {'keyword': '事務員', 'adj': '不倫したい', 'noun': '女子事務員', 'reason': '仕事が退屈で刺激的なセックスをしたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'office-clerk', 'id': '162', 'pro': '事務員 セックス', 'particle': 'の'},
    {'keyword': 'アーティスト', 'adj': 'SEX好きな', 'noun': '女性アーティスト', 'reason': '感性豊かで性欲も旺盛だから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'musician', 'id': '163', 'pro': 'アーティスト セックス', 'particle': 'の'},
    {'keyword': '芸術家', 'adj': '経験豊富な', 'noun': '女性芸術家', 'reason': 'セックス経験が豊富でいろんな男性とやりたいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'artist', 'id': '164', 'pro': '芸術家 セックス', 'particle': 'の'},
    {'keyword': '高校教師', 'adj': '性欲が強い', 'noun': '高校教師', 'reason': '生徒とはセックスできなくて性欲が溜まっているから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'high-school-teacher', 'id': '165', 'pro': '高校教師 セックス', 'particle': 'の'},
    {'keyword': 'ボランティア', 'adj': 'セックスレスの', 'noun': '女性ボランティア', 'reason': '最近セックスをしていなくて性欲が溜まっているから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'volunteer', 'id': '166', 'pro': 'ボランティア セックス', 'particle': 'の'},
    {'keyword': '露出狂', 'adj': '野外好きな', 'noun': '露出<!--woman-n-->', 'reason': '露出セックスができる相手を探しているから', 't_cat': 'p',
     'ms': 'm', 't_age': 'n', 'look': False, 'eng': 'flasher', 'id': '167', 'pro': '露出 セックス', 'particle': 'の'},
    {'keyword': 'ママ友', 'adj': '不倫願望がある', 'noun': 'ママ友', 'reason': '子育てが退屈で刺激が欲しいから', 't_cat': 's', 'ms': 's',
     't_age': 'n',
     'look': False, 'eng': 'mother-friend', 'id': '168', 'pro': 'ママ友 セックス', 'particle': 'の'},
    {'keyword': 'デブス', 'adj': '巨乳の', 'noun': 'デブス女子', 'reason': 'セックスしてくれる男性がいなくて、セックスレスだから', 't_cat': 'l', 'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'plump-and-ugly', 'id': '169', 'pro': 'デブス セックス', 'particle': 'の'},
    {'keyword': '不動産レディ', 'adj': '人妻の', 'noun': '不動産営業レディ', 'reason': '営業の仕事が大変でストレスが溜まっているから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'real-estate-sales-lady', 'id': '170', 'pro': '不動産レディ セックス', 'particle': 'の'},
    {'keyword': '女子社員', 'adj': 'フェラ好きな', 'noun': '女子社員', 'reason': '会社では出会いがなくて、ネットでセックスできる相手を探しているから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'female-employee', 'id': '171', 'pro': '女子社員 セックス',
     'particle': 'の'},
    {'keyword': 'ウェイトレス', 'adj': '巨乳', 'noun': 'ウェイトレス', 'reason': '仕事で嫌なことがあってセックスして解消したいから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'waitress', 'id': '172', 'pro': 'ウェイトレス セックス', 'particle': 'の'},
    {'keyword': 'アスリート', 'adj': 'イキやすい', 'noun': '女性アスリート', 'reason': '体力があって、長時間セックスしないと満足できないから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'athlete', 'id': '173', 'pro': 'アスリート セックス', 'particle': 'の'},
    {'keyword': 'コンパニオン', 'adj': 'ピンクな', 'noun': 'コンパニオン', 'reason': '男性からチヤホヤされる仕事だけどなかなか相手がいないから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'companion', 'id': '174', 'pro': 'コンパニオン セックス', 'particle': 'の'},
    {'keyword': '女子アナ', 'adj': 'エロい', 'noun': '女子アナ', 'reason': '恋愛ができなくて、素人男性とこっそりセックスを楽しみたいから', 't_cat': 'j',
     'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'newscaster', 'id': '175', 'pro': '女子アナ セックス', 'particle': 'の'},
    {'keyword': 'ノーパン', 'adj': 'ドMな', 'noun': 'ノーパン女子', 'reason': '羞恥プレイを楽しめる男性を探しているから', 't_cat': 'p', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'go-commando', 'id': '176', 'pro': 'ノーパン セックス', 'particle': 'の'},
    {'keyword': 'ノーブラ', 'adj': '巨乳の', 'noun': 'ノーブラ<!--woman-n-->', 'reason': '興奮できるセックスができる男性を探しているから', 't_cat': 'p',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'braless', 'id': '177', 'pro': 'ノーブラ セックス', 'particle': 'の'},
    {'keyword': 'バスガイド', 'adj': 'お姉さんの', 'noun': 'バスガイド', 'reason': '仕事でなかなか恋愛ができなくてヤリモクの出会いを探しているから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'bus-tour-guide', 'id': '178', 'pro': 'バスガイド セックス',
     'particle': 'の'},
    {'keyword': '秘書', 'adj': '美人な', 'noun': '女性秘書', 'reason': '真面目そうでいて実はかなりセックスが好きで相手を探しているから', 't_cat': 'j',
     'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'secretary', 'id': '179', 'pro': '秘書 セックス', 'particle': 'の'},
    {'keyword': '美人女将', 'adj': '人妻の', 'noun': '美人女将', 'reason': '旅館の忙しい仕事だけど、性欲旺盛でやれる男性を探しているから', 't_cat': 'j',
     'ms': 's',
     't_age': 'n', 'look': True, 'eng': 'landlady', 'id': '180', 'pro': '美人女将 セックス', 'particle': 'の'},
    {'keyword': '同僚', 'adj': '会社の', 'noun': '同僚の<!--woman-->', 'reason': '会社では出会いを探せなくて出会い系で相手を探してるから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'coworker', 'id': '181', 'pro': '同僚 セックス', 'particle': 'の'},
    {'keyword': '肉食女子', 'adj': 'SEX好きな', 'noun': '肉食系痴女', 'reason': '誰でも良くてとりあえず気持ちいいセックスをできる男性と出会いたいから', 't_cat': 'p',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'carnivorous-girl', 'id': '182', 'pro': '肉食女子 セックス',
     'particle': 'の'},
    {'keyword': '草食女子', 'adj': 'レスな', 'noun': '草食系女子', 'reason': '草食でセックスレスだけど、男性から誘われたらセックスするから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'grazer-girl', 'id': '183', 'pro': '草食女子 セックス', 'particle': 'の'},
    {'keyword': 'BL女子', 'adj': 'メガネの', 'noun': 'BL女子', 'reason': 'BLでいつも見ている男性の体をじっくりと見てみたいから', 't_cat': 'c', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'boys-love', 'id': '184', 'pro': 'BL女子 セックス', 'particle': 'の'},
    {'keyword': 'アラフィフ', 'adj': '閉経前の', 'noun': 'アラフィフ女性', 'reason': '閉経する前に思いっきりセックスを楽しみたいから', 't_cat': 'a', 'ms': 's',
     't_age': 'o', 'look': False, 'eng': '50-something', 'id': '185', 'pro': 'アラフィフ セックス', 'particle': 'の'},
    {'keyword': '新社会人', 'adj': '彼氏がいない', 'noun': '新社会人の<!--woman-->',
     'reason': '新しい環境でリアルの出会いがなくて、ネットでセックスありの出会いを探しているから', 't_cat': 'j', 'ms': 's', 't_age': 'y', 'look': False,
     'eng': 'new-members-of-society', 'id': '186', 'pro': '新社会人 セックス', 'particle': 'の'},
    {'keyword': '新入社員', 'adj': '浮気好きの', 'noun': '女子新入社員', 'reason': '彼氏がいるけど、他の男性とエロいセックスを楽しみたいから', 't_cat': 'j',
     'ms': 's', 't_age': 'y', 'look': False, 'eng': 'incoming-employee', 'id': '187', 'pro': '新入社員 セックス',
     'particle': 'の'},
    {'keyword': '合法ロリ', 'adj': '実はエロい', 'noun': '合法ロリ女子', 'reason': '18歳になっておおっぴらにセックスができて、とりあえずセックスしまくりたいから',
     't_cat': 'c', 'ms': 's', 't_age': 'y', 'look': False, 'eng': 'legal-lolita', 'id': '188', 'pro': '合法ロリ セックス',
     'particle': 'の'},
    {'keyword': '不思議系', 'adj': '美少女の', 'noun': '不思議系女子', 'reason': '天然の不思議系だけど、中身はかなりエロくてセックス好きだから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'weird', 'id': '189', 'pro': '不思議系 セックス', 'particle': 'の'},
    {'keyword': '女上司', 'adj': '人妻の', 'noun': '女上司', 'reason': '普段は真面目にしているけど、その分ストレスと性欲が溜まっているから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'female-boss', 'id': '190', 'pro': '女上司 セックス', 'particle': 'の'},
    {'keyword': '既婚者', 'adj': '不倫好きな', 'noun': '既婚女性', 'reason': '夫以外の男性のモノにかなり興味があるから', 't_cat': 's', 'ms': 'm',
     't_age': 'n', 'look': False, 'eng': 'married', 'id': '191', 'pro': '既婚者 セックス', 'particle': 'の'},
    {'keyword': 'ユルフワ', 'adj': '実はエッチな', 'noun': 'ユルフワ女子', 'reason': '外見はユルフワだけど、内面は他の女性と同じでエロいから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'yurufuwa', 'id': '192', 'pro': 'ユルフワ セックス', 'particle': 'な'},
    {'keyword': '若い女の子', 'adj': '不倫したい', 'noun': '若い<!--woman-y-->', 'reason': '年上の優しい男性と気持ちいいセックスをしたいから', 't_cat': 'a',
     'ms': 's', 't_age': 'y', 'look': False, 'eng': 'young-girl', 'id': '193', 'pro': '若い 女の子 セックス', 'particle': 'の'},
    {'keyword': '18歳', 'adj': '交際できる', 'noun': '合法な18歳の<!--woman-y-->', 'reason': 'セックスを覚えたばかりで色々な男性とセックスしたいから',
     't_cat': 'a', 'ms': 's', 't_age': 'y', 'look': False, 'eng': 'eighteen', 'id': '194', 'pro': '18歳 セックス',
     'particle': 'の'},
    {'keyword': '韓国人', 'adj': '彼氏がいる', 'noun': '韓国人の<!--woman-->', 'reason': '日本人男性とのセックスに興味があるから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'korean', 'id': '195', 'pro': '韓国人 セックス', 'particle': 'の'},
    {'keyword': '中国人', 'adj': '恋愛好きの', 'noun': '中国人の<!--woman-->', 'reason': '優しい日本人男性と仲良くなりたいから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'chinese', 'id': '196', 'pro': '中国人 セックス', 'particle': 'の'},
    {'keyword': 'ロシア人', 'adj': 'ウクライナや', 'noun': 'ロシア人の<!--woman-->', 'reason': '真面目な日本人男性に魅力を感じているから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'russian', 'id': '197', 'pro': 'ロシア人 セックス', 'particle': 'の'},
    {'keyword': '水商売', 'adj': 'SEX好きな', 'noun': '水商売の<!--woman-o-->', 'reason': '夜遅くまで働いていてストレスが溜まっているから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'nightclub', 'id': '198', 'pro': '水商売 セックス', 'particle': 'の'},
    {'keyword': '女子高生っぽい<!--woman-y-->', 'adj': '素人の', 'noun': '女子高生っぽい<!--woman-y-->',
     'reason': '優しい男性と満足できるセックスがしたいから', 't_cat': 's', 'ms': 's', 't_age': 'y', 'look': False,
     'eng': 'high-school-student',
     'id': '199', 'pro': '女子高生 セックス', 'particle': 'の'},
    {'keyword': 'JKっぽい<!--woman-y-->', 'adj': 'エロい', 'noun': 'JKっぽい<!--woman-y-->',
     'reason': '精神的に幼くて年上男性とのセックスに憧れているから', 't_cat': 's', 'ms': 's', 't_age': 'y', 'look': False,
     'eng': 'jk', 'id': '200', 'pro': 'JK セックス', 'particle': 'の'},
    {'keyword': 'JCっぽい<!--woman-y-->', 'adj': 'ロリの', 'noun': 'JCっぽい<!--woman-y-->',
     'reason': 'ロリっぽい外見のためになかなかセックスの相手が見つからないから', 't_cat': 's', 'ms': 's', 't_age': 'y', 'look': False, 'eng': 'jc',
     'id': '201', 'pro': 'JC セックス', 'particle': 'の'},
    {'keyword': 'ガテン系', 'adj': '引き締まった', 'noun': 'ガテン系の<!--woman-->', 'reason': '性欲が有り余っていて満足できるくらいセックスしたいと考えているから',
     't_cat': 'j', 'ms': 's', 't_age': 'n', 'look': False, 'eng': 'physical-labor', 'id': '202', 'pro': 'ガテン系 セックス',
     'particle': 'の'},
    {'keyword': '婦人警官', 'adj': '良い体の', 'noun': '婦人警官', 'reason': '忙しくて厳しい仕事のストレスを解消できるのはセックスしかないから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'policewoman', 'id': '203', 'pro': '婦人警官 セックス', 'particle': 'の'},
    {'keyword': 'ダンサー', 'adj': 'エッチな', 'noun': 'ダンサー', 'reason': 'レッスンなどで忙しくてなかなか彼氏を作れずムラムラしているから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'dancer', 'id': '204', 'pro': 'ダンサー セックス', 'particle': 'の'},
    {'keyword': '声優', 'adj': '巨乳の', 'noun': '女性声優', 'reason': '仕事柄彼氏を作りにくくて、セックスの相手に恵まれていないから', 't_cat': 'j', 'ms': 's',
     't_age': 'n', 'look': False, 'eng': 'voice-actor', 'id': '205', 'pro': '声優 セックス', 'particle': 'の'},
    {'keyword': '日本人', 'adj': '素人の', 'noun': '日本人<!--woman-n-->', 'reason': 'セックスをするなら同じ日本人がやっぱりいいから', 't_cat': 'c',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'japanese', 'id': '206', 'pro': '日本人 セックス', 'particle': 'の'},
    {'keyword': 'ホテルウーマン', 'adj': '美人の', 'noun': 'ホテルウーマン', 'reason': '時間が不規則な仕事なので、都合よくセックスできる男性を探しているから',
     't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'hotel-woman', 'id': '207', 'pro': 'ホテルウーマン セックス', 'particle': 'の'},
    {'keyword': 'デリヘル嬢', 'adj': '巨乳の', 'noun': 'デリヘル嬢', 'reason': '仕事では本番ができなくて挿入までできる相手を探しているから', 't_cat': 'j',
     'ms': 's', 't_age': 'n', 'look': False, 'eng': 'prostitution', 'id': '208', 'pro': 'デリヘル嬢 セックス', 'particle': 'の'}]
